### ISSUE TITLE
[BUG] Audio does not resume after spoken directions using Google Maps Apple Carplay iOS17

### ISSUE THREAD

**Issue by mgb744** [LeoKlaus/plappa#100]
**Describe the bug**
While driving with iPhone 15 Pro Max on iOS17.4.1 using and plappa 1.1.5 after a spoken turn by turn direction is give the auiobook stops playing but never resumes. iPhone on wired connection book is locally downloaded.

**To Reproduce**
1. connect phone to carplay
2. add destination with spoken directions
3. start audiobook
4. at next spoken direction book pauses while direction given (as expected)
5. after direction ends book never resumes.

**Expected behavior**
book should resume playing after spoken direction

**Environment(please complete the following information):**
 - Device: iPhone15ProMax
 - OS: [e.g. iOS17.4.1
 - Google Maps 6.114.3 
 - plappa 1.1.5 
 - Local downloaded book

**Comment by LeoKlaus** [comment]
Hey mgb744, thank you for reporting this and sorry for the late response!

Can you check if this happens with all audiobooks or just that one? This issue has been reported in the past but others have told me that the fixes I implemented have resolved it (should've been version 1.1.3 or 4, iirc).

**Comment by LeoKlaus** [comment]
I'm closing this for now. If the issue still persists, feel free to reopen.
