### ISSUE TITLE
[BUG] Download process is displayed incorrectly

### ISSUE THREAD

**Issue by mrburns-42** [LeoKlaus/plappa#101]
**Describe the bug**
With the latest update, the download now works in the background, thank you very much for this. However, the download overview remains stuck in the overview. I have the following view after downloading a book.

**To Reproduce**
1. Go to an Audiobook
2. Click on Download
3. Click on home
4. Click on the Download-Butten in the upper left corner
5. Look on the Download-Process
6. Switch the App in Background
7. Open the App some minutes later
8. You see the downloaded book in the overview
9. Click on the Download-Button in the upper left corner
10. You can see that the download process is not finished, although it has already been completed

**Expected behavior**
That the download is displayed as completed.

**Screenshots**
his is what it looks like when the book has finished downloading:

![IMG_6848](https://github.com/LeoKlaus/plappa/assets/786982/976d410d-fca0-4319-811a-24ed545a8782)

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.4.1
 - Version 1.1.6 (3)
 - Server Version ABS 2.9.0

**Additional context**

**Comment by LeoKlaus** [comment]
This should be fixed with the latest release of 1.4.0. If this issue reappears, feel free to reopen this.
