### ISSUE TITLE
[BUG] Plappa does not use the local file in certain situations and streams instead

### ISSUE THREAD

**Issue by mrburns-42** [LeoKlaus/plappa#105]
**Describe the bug**
I listened to an audiobook on stream. I downloaded the audiobook at the same time. After completing the download, I paused and restarted the audiobook to use the local file instead of the stream. Plappa continues to use the stream instead of the local file.

It only works when the app is restarted or alternatively the player is closed completely.

**To Reproduce**
1. Go to an audiobook.
2. Click on Download.
3. Click on Play.

After the download finished:

4. Pause the audiobook.
5. Resume the audiobook.

**Expected behavior**
Ideally, you should switch to an audiobook after downloading it. At least at the moment when the audiobook is paused and then continued.

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.4.1
 - Version 1.1.6 (3)
 - Server Version ABS 2.9.0

**Comment by LeoKlaus** [comment]
plappa will switch to the downloaded file automatically while playing, you don't have to pause or anything.

I believe the only way to reproduce this is to stop playback and without going back from the detail view start it again.

I'll see what's causing this and implement a fix.

**Comment by LeoKlaus** [comment]
Ist just released an update to TestFlight that fixes this issue.
