### ISSUE TITLE
[Feature Request] Restrict Number of Active Downloads

### ISSUE THREAD

**Issue by punkcoder** [LeoKlaus/plappa#111]
What?
The ability to throttle the number of active downloads, queueing other downloads.

Why?
Some audiobooks come in many parts (40+ separate files) on NAS with HDD this causes poor performance because of disk thrashing.

Thank you for the fantastic work that you are doing.

**Comment by LeoKlaus** [comment]
Great catch, I'll make sure to add something like that.

**Comment by LeoKlaus** [comment]
I've just released a beta update with a new download system. From now on, files will be downloaded sequentially and in order.

If you want to try it, you can join the TestFlight beta here: https://testflight.apple.com/join/oSAekRD5
