### ISSUE TITLE
[enhancement] Add 2.5x and 3x playback speed options

### ISSUE THREAD

**Issue by pceimpulsive** [LeoKlaus/plappa#113]
Hi,

I am wondering if it's possible to introduce some higher playback speed options?

I can see the current release supports 0.5x through 2x. Is it possible to add 2.5x and 3x playback speeds at all?

**Comment by LeoKlaus** [comment]
Hi pceimpulsive,

You can already do that :)
Just go to the settings tab, there's an option "Change playback rates".
You can enter any decimal number you like.

Let me know if there's anything else.
