### ISSUE TITLE
[BUG] CarPlay: selecting a book does not change to media playing screen

### ISSUE THREAD

**Issue by timespacedecay** [LeoKlaus/plappa#120]
**Describe the bug**
In CarPlay, selecting a book does not change to media playing screen. The book begins playing, but the screen remains on the library screen. 

**To Reproduce**
1. Open Plappa in CarPlay
2. Select a book
3. Book starts to play, but screen remains on the library screen and does not change to the media playing screen. 

**Expected behavior**
After selecting a book, I would expect the screen to switch to the media playing screen as the book starts to play. 

**Screenshots**
Can be provided if needed. 

**Logs**
N/A

**Environment(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.5.1
 - Plappa Version: 1.1.5
 - AudioBookShelf Server Version: 2.10.1

**Comment by mrburns-42** [comment]
I have the same problem. However, I only have this when Plappa is on in full screen mode. If it is in split screen, e.g. with Apple maps, then the buttons work.

**Comment by LeoKlaus** [comment]
Thank you for reporting this. The logic to switch to the now playing screen is in place but not called for some reason. I'm currently investigating why.

**Comment by LeoKlaus** [comment]
Found the issue and implemented a fix. It will release to TestFlight shortly and to the AppStore in the coming days.
