### ISSUE TITLE
[Feature Request] Integration with iOS Shortcuts/Automation

### ISSUE THREAD

**Issue by ddman2** [LeoKlaus/plappa#125]
### **_Feature Request: Integration with iOS Shortcuts/Automation_**

**Summary**
It would be great to have integration of Plappa with iOS Shortcuts/Automation to enable users to automate tasks such as starting the playback of the current audiobook.

**Description**
Please provide support for iOS Shortcuts by exposing actions that can be used within the Shortcuts app. Specifically, the ability to:

    Start playing the current audiobook.
    Pause playback.
    Skip to the next chapter.

These actions will allow users to create custom automation, such as starting audiobook playback when connecting to CarPlay.

For more information on how to integrate with the Shortcuts app, please refer to Apple's [Shortcuts API documentation](https://developer.apple.com/documentation/sirikit).

**Implementation**
    Expose Actions: Add actions like "Start Current Audiobook," "Pause Playback," and "Skip Chapter" to the iOS Shortcuts app.

Thank you for considering this feature request.

**Comment by LeoKlaus** [comment]
I love this idea! I'm currently using a shortcut myself to start playback whenever my phone connects to my car stereo but this would be much more elegant.

**Comment by ddman2** [comment]
Which action(s) are you using to initiate playback?  I am currently using:

- "Open [Plappa]"
- "'Play' on [Phone]" 

and it's not always working.

**Comment by LeoKlaus** [comment]
> Which action(s) are you using to initiate playback?  I am currently using:
> 
> - "Open [Plappa]"
> - "'Play' on [Phone]" 
> 
> and it's not always working.

I'm using just the play action to resume whatever was playing before.

It might fail in your case because plappa can take a second to load the player after it is launched. Adding a one or two second delay should make the shortcut work more reliably.


I'm currently experimenting with the AppIntents for plappa, but I haven't been able to start playback when the app is closed yet.

**Comment by LeoKlaus** [comment]
I've got everything working now and have included some intents with the upcoming 1.3.0 update.
It should be available on TestFlight in the coming days.

**Comment by sevenlayercookie** [comment]
> I've got everything working now and have included some intents with the upcoming 1.3.0 update.
> 
> It should be available on TestFlight in the coming days.

You're a machine!!

**Comment by LeoKlaus** [comment]
The update is currently in the experimental TestFlight branch and will hit the regular beta channel and the AppStore fairly soon. I'll close this for now.

If you encounter any issues with the shortcuts, feel free to reopen.
