### ISSUE TITLE
[BUG] Progress from ABS is not synced

### ISSUE THREAD

**Issue by LeoKlaus** [LeoKlaus/plappa#128]
As mentioned by @mindtakerr in #122

**Comment by mindtakerr** [comment]
You're right. It must have been a fluke. I just tried it
Again and it updated my progress from ABS with no problem. Thanks!

**Comment by LeoKlaus** [comment]
Thank you for the update. I'll close this then. If the issue pops up again, feel free to reopen.


Some details regarding progress syncing:
- plappa will try to sync progress whenever it moves to the foreground
- Progress syncing relies on timestamps. This means that if either your phone or server have the wrong time(zone), new progress might be seen as outdated
- ABS (at least the WebUI) only saves progress periodically. If you skip a few chapters for example, the progress will only be saved once you listen for about 10s
- plappa generally saves progress with every user interaction (play/pause, scrubbing or skipping) and will try to sync changes as soon as possible


Most of these are very unlikely to ever impact regular listening, but especially when trying to troubleshoot missing progress and switching back and forth, you might see progress syncing not work as expected.
