### ISSUE TITLE
[BUG] Seek bar not functional on iOS 18

### ISSUE THREAD

**Issue by sevenlayercookie** [LeoKlaus/plappa#129]
**Describe the bug**
Dragging the seek bar does not change the time location of playing audio.

**To Reproduce**
1. Start playing an audiobook.
2. Click on the seek bar and drag forward or backwards.
3. Playing location does not change.

**Expected behavior**
if I drag the seek bar forward to five minutes, for instance, I expect the audiobook to begin playing at five minutes.

**Screenshots**
https://github.com/LeoKlaus/plappa/assets/15989705/542b54b5-6013-4021-809a-43d54913f997
**Logs**
NA

**Environment(please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 18.0 beta
 - Version 1.1.6
 - Server Version ABS 2.9.0

**Additional context**
I don't remember this being an issue with earlier versions of plappa. Also, this seems to be an issue whether the book is streaming from remote server or downloaded locally.

**Comment by LeoKlaus** [comment]
I have noticed the same issue on my phone, but it only occurs on iOS18.

There has been no change to the playback controls in recent updates, so this is probably a bug in iOS18.

**Comment by LeoKlaus** [comment]
I've looked into this and developed a workaround. It'll release to TestFlight once the 1.2.0 update is approved by Apple.

iOS 18 has changed the way the `.onLongPressGesture` modifier is called in SwiftUI, leading to the progress being reset whenever you let go of the handle.
