### ISSUE TITLE
Impossibile listen file.opus

### ISSUE THREAD

**Issue by Nikibasso94** [LeoKlaus/plappa#130]
Impossible ti riproduce file .opus

**Environment(please complete the following information):**
 - Device: IPhone 14 pro Max 
 - OS: IOS 17.5.1
 - Version app 1.1.6
 - Server Version audiobook selfhosted 2.10.1

audiobooks web page riproduce file

**Comment by LeoKlaus** [comment]
Hey Nikibasso94,

I think I found the underlying issue. I've implemented a fix with the latest TestFlight release (1.3.0 build 6).
If you want to try it, you can join the TestFlight beta here: https://testflight.apple.com/join/oSAekRD5

The fix will also be released with the next AppStore update in the coming weeks.

**Comment by LeoKlaus** [comment]
Closing this now. If the issue still exists, feel free to reopen.
