### ISSUE TITLE
[FEATURE] download chapters sequentially

### ISSUE THREAD

**Issue by sevenlayercookie** [LeoKlaus/plappa#131]
When downloading a an entire book, chapterized mp3s are currently downloaded all simultaneously and they finish in random order (e.g. chapter 23.mp3 downloads before chapter 1.mp3). I have a few suggestions.

1. By default when downloading a whole book, the chapters should be downloaded sequentially to allow listening to the book from the beginning as soon as possible (especially on a slow connection).

2. Download only 1 chapter at a time (or maybe up to 5 chapters or so simultaneously, depending on chapter file size and connection speed), again to prioritize downloading the first 1-5 chapters first and allow listening.

3. Not as important, but would be nice to be able to drag to arrange order of downloads page in order to prioritize a different chapter first (for instance if the user would like to download the whole book, but start with chapter 12 since they happen to be at that chapter in the book they are reading)

![image](https://github.com/LeoKlaus/plappa/assets/15989705/f8504f7a-637a-4578-b884-4c1f278069b7)

**Comment by LeoKlaus** [comment]
I feel like this issue would be fixed with #132, so I'm closing this for now (files are downloaded sequentially from 1.4.0 build 35 on).

If you feel like this should stay a separate feature request, feel free to reopen.
