### ISSUE TITLE
[FEATURE]  pause/resume/cancel all downloads

### ISSUE THREAD

**Issue by sevenlayercookie** [LeoKlaus/plappa#133]
- **Issue**: sometimes I accidentally initiate download of entire book, perhaps when I'm on a limited data connection. Currently have to go through and manually cancel each .mp3 chapter download.
- **Solution**: have "pause all" "resume all" and "cancel all" buttons on the download page (or some variation that allows for these actions to be performed on all .mp3 chapters at once).

![image](https://github.com/LeoKlaus/plappa/assets/15989705/d38e3bb1-3572-4bdd-a58e-4bd8509eefd4)

**Comment by LeoKlaus** [comment]
Hey, sorry for the late response.

I've been working on a rewrite of the download handling and have just released the first version to TestFlight (only the experimental channel for now).
With this update, there's still no button to pause/cancel all, but downloads for a single book are grouped and treated as one now, allowing you to pause/cancel with a single tap.

If you want to try it, you can join the TestFlight beta here: https://testflight.apple.com/join/oSAekRD5
