### ISSUE TITLE
[FEATURE] password manager support

### ISSUE THREAD

**Issue by sevenlayercookie** [LeoKlaus/plappa#134]
iOS doesn't seem to detect the username/password boxes when logging into the server as username/password forms, so the iOS password manager isn't being triggered (for storing or recalling the password).

Is it possible to tag these forms so that iOS will prompt to remember the password?

**Comment by LeoKlaus** [comment]
Both the username and password fields are marked as such and iOS will give you the option to open your password manager:
![image](https://github.com/LeoKlaus/plappa/assets/66492595/59481393-66af-4caa-8659-0252389a6bb0)

Automatically filling and or saving the data is sadly not possible, as this requires the "associated domain" to be set at compile time.

**Comment by sevenlayercookie** [comment]
> Both the username and password fields are marked as such and iOS will give you the option to open your password manager:
> 
> ![image](https://github.com/LeoKlaus/plappa/assets/66492595/59481393-66af-4caa-8659-0252389a6bb0)
> 
> 
> 
> Automatically filling and or saving the data is sadly not possible, as this requires the "associated domain" to be set at compile time.

Ah I see I suppose that makes sense. Thanks for the explanation
