### ISSUE TITLE
[BUG] when going to Collections App Crashes

### ISSUE THREAD

**Issue by JanM802** [LeoKlaus/plappa#138]
Hello,

the App Crashes on an IPhone 12 when I open Collections. On all my other Devices there is no Problem with opening the Collections Tab. All other Devices are running IOS 18. The IPhone 12 specs are in the following Screenshot. I also recorded the Moment of the crash. 

The Logs are cleared after the Crash.

https://github.com/LeoKlaus/plappa/assets/163157651/1900f79c-7216-44bd-bf79-55e8d554afe1

![IMG_2684](https://github.com/LeoKlaus/plappa/assets/163157651/55237b94-fca7-4a14-8e8d-57c8e524af8f)

**Comment by LeoKlaus** [comment]
Thank you for reporting this.

There's an issue causing excessive memory usage in the collection tabs (Series, Collections and Playlists) in the current version of plappa.

I've fixed this issue in a recent TestFlight update, which you can download here:
https://testflight.apple.com/join/oSAekRD5

Could you try updating plappa on that device and see if that fixes the issue?

**Comment by JanM802** [comment]
Hello, 
Thank you for the fast response, unfortunately I'm already using the test flight version. I also tried downgrading but this as well didn't work.

**Comment by JanM802** [comment]
I just upgraded to iOS 18 on the IPhone too and now everything works fine.
