### ISSUE TITLE
[FEATURE] Sleep timer - End of NEXT chapter

### ISSUE THREAD

**Issue by migol** [LeoKlaus/plappa#139]
As title suggests, I often use End of chapter as a sleep timer, but I would really love to have ability to do "end of next chapter" as sometimes I end up with like 5 minutes left in chapter or very short interlude one.

**Comment by LeoKlaus** [comment]
I've just implemented this. It will be available with the next update.

**Comment by migol** [comment]
Amazing! Thank you!
