### ISSUE TITLE
[Feature Request] Adjust Remaining Time to Account for Playback Speed

### ISSUE THREAD

**Issue by CDeLeon94** [LeoKlaus/plappa#140]
As a person with ADHD I sometimes find myself listening to my book club books literally at the last minute. 

Being able to see how much longer is left in the chapter, and the duration of other chapters, with the adjusted playback speed would be greatly beneficial for finding the right playback speed. 

I don't want to listen to things faster than necessary, so that its easier to follow, but I'd also don't want to miscalculate and end up not finishing the chapters in time. 

Audiobookshelf's web player is an example of such an implementation. (My only issue with that one was that before I knew it did that, I once adjusted my playback speed based on the assumption that the duration was the base 1x duration)

**Comment by LeoKlaus** [comment]
Hey Leon, thanks for reaching out!

I'll make sure to add this.

**Comment by LeoKlaus** [comment]
1.3.0 is now live with this change!
