### ISSUE TITLE
[BUG] Playback state get's mixed up

### ISSUE THREAD

**Issue by eDimoon** [LeoKlaus/plappa#141]
**Describe the bug**
Since updating the ABS-Server to 2.10.1 via Docker-image, the progress in books get's mixed up / wrongly set.
The update to plappa version 1.2.0 also happened nearly at the same time. For the reason mentioned under Additional, i don't think this is on the ABS end. (But please correct me if i am wrong.)

**To Reproduce**
1. Play a book in your library
2. Pause the book
3. Check the progress either on ABS or plappa itself.

PS: As i am writing this bug report,  the book is now marked completely played, but the app seems to still remember the local state.
As shown in screenshot 3.

**Expected behavior**
If a book get's played, at the moment of pause (or maybe a small delay) i expect the dashboard to represent the listening state. Either finished, or in the middle somewhere.

**Screenshots**
![grafik](https://github.com/LeoKlaus/plappa/assets/110928767/88607bdb-b94f-45e3-827f-384d3b11ccb4)
![grafik](https://github.com/LeoKlaus/plappa/assets/110928767/2f17fdd5-4693-475d-97de-619a096ccf4c)

Player shows the book as finished, but on the bottom, the "real" status remains and still holds the correct listening status.
![grafik](https://github.com/LeoKlaus/plappa/assets/110928767/ddf62e14-8b0a-4373-bb56-c182ae7eeb3c)

**Environment**
 - Device: [iPhone 11 Pro Max]
 - OS: [iOS 17.5.1]
 - Version [1.2.0]
 - Server Version [Audiobookshelf 2.10.1]

**Additional Info**
A rebuild of the container and going back to a version before, does not change this behaviour.

If this has been adressed already and i didn't see it in the issue tracker, please feel free to close the report.

**Comment by LeoKlaus** [comment]
Hi Jan, thank you for reporting this.

There's an issue causing plappa to store playback states with a duration of 1 seconds (the current time is correctly saved), which leads to the progress (current time/duration) to always be 100%. The time itself is saved correctly.

I've already fixed this in the latest TestFlight release, I'll release an update to the AppStore asap.

If you want to try the TestFlight release, you can do so here: https://testflight.apple.com/join/oSAekRD5

**Comment by eDimoon** [comment]
Hi Leo,
thanks for the fast response and thanks for the fix. I'll mark it as closed, since the issue should vanish in the next release.
Thanks again. :)
