### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by stickystyle** [LeoKlaus/plappa#143]
**Describe the bug**
Chapters are not shown in a book that has not been played yet on the device. Books that have been played already do show the chapters. Books that have been marked read on the server exhibit the same behavior. 

**To Reproduce**
open a unread (on the device) book. 

**Expected behavior**
chapters shown

**Screenshots**
![IMG_3528](https://github.com/LeoKlaus/plappa/assets/858414/99f9fca3-8b55-43a0-b6e1-42046fd285c3)

**Logs**

[6/28/2024, 07:26] [AudioBookShelfAPIHandler] Couldn't post closed session, server returned 404. URL: https://xxx.net/api/session/E6556589-87E2-415C-AFFD-6AE924601D91/close
[6/28/2024, 07:28] [AudioBookShelfAPIHandler] Trying to convert old chapters
[6/28/2024, 07:28] [AudioBookShelfAPIHandler] Trying to convert old chapters

**Environment(please complete the following information):**
 - Device: iphone13
 - OS: 17.5.1
 - Version beta 1.3.0 (13)
 - Server Version AB 2.10.1

**Additional context**

**Comment by LeoKlaus** [comment]
Hi Ryan, thank you for reporting this.

Looks like plappa is trying to read metadata it saved in an older version of the app. Can you try logging out and back in to your server (or reinstalling the app)?

**Comment by stickystyle** [comment]
Logging out and back in resolved it 👍

**Comment by LeoKlaus** [comment]
Great, thank you for the update. I'll close this for now.
