### ISSUE TITLE
[FEATURE REQUEST] Show progress of whole book

### ISSUE THREAD

**Issue by MadWalnut** [LeoKlaus/plappa#146]
It would be great to be able to see the remaining time / progress of the whole book on the book detail screen and / or in the playback screen. Currently the only indicator on how far along you are in a book is the small overlayed progress bar on the cover on the home screen. In the playback screen it only shows the time remaining in the current chapter, not the whole book.

The ABS app displays this like this on the book detail page:

![image](https://github.com/LeoKlaus/plappa/assets/33835479/aa39c7a2-3861-48a2-9f83-8b2237ee5f49)

This feature request would probably also be solved by implementing #56, at least on the playback page.

Thanks for the app and keep up the great work!

**Comment by pax0707** [comment]
Came here to request this exact feature.

**Comment by LeoKlaus** [comment]
I've implemented this with a recent TestFlight release, it will be available with the next AppStore update.
