### ISSUE TITLE
[BUG] When the audiobook starts on group of AppleTV & HomePod, the TV is switched on.

### ISSUE THREAD

**Issue by mrburns-42** [LeoKlaus/plappa#150]
**Describe the bug**
In one room, the AppleTV is paired with a HomePod for audio output. If I now connect the iPhone to the AppleTV and HomePod group via AirPlay, the TV is automatically switched on when I start playback under Plappa.

With Prologue and Apple Music, for example, I don't have this problem, here only the audio output is started on the HomePod and the TV remains off.

**To Reproduce**
1. Connect the iPhone per Airplay with the group of HomePod & AppleTV
2. Start a audiobook in Plappa
3. See error

**Expected behavior**
That only the audio is output on the HomePod, the TV remains off.

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.5.1 
 - Version 1.4.0 (23)
 - Server Version ABS 2.11.0

**Comment by LeoKlaus** [comment]
I just released 1.4.0 build 24 to TestFlight. Can you check if the same issue appears there?

**Comment by mrburns-42** [comment]
I have tried it, it works now. Many thanks for the quick remedy.
