### ISSUE TITLE
[Feature Request] Filter library by read/unread, downloaded/not downloaded

### ISSUE THREAD

**Issue by glycerine1** [LeoKlaus/plappa#152]
iOS client app.

Under Books menu, add a filter for read/unread and downloaded/downloaded.  The icons are nice but with a larger library, it can be cumbersome to be able to quickly tell what books you have read/downloaded for quick selection.

**Comment by LeoKlaus** [comment]
Definitely a great idea and shouldn't be hard to add!

**Comment by LeoKlaus** [comment]
I've added both this and #153 with the latest TestFlight beta update (1.4.0 Build 29). If you're not part of the TestFlight beta, you can check it out here: https://testflight.apple.com/join/oSAekRD5
