### ISSUE TITLE
[Feature Request] Option to keep screen awake

### ISSUE THREAD

**Issue by glycerine1** [LeoKlaus/plappa#153]
iOS client.

A preference toggle to keep the screen awake. Keep player display on screen to be able to quickly access controls and audiobook information at a glance. Use case: iPad plugged in and set on desk. Would figure this would work very similar to the "Keep screen awake" option in the Pocket Casts app.

**Comment by LeoKlaus** [comment]
This shouldn't be to hard to add, I'll let you know once I know more!

**Comment by LeoKlaus** [comment]
Implemented with 1.4.0 Build 29. You have to enable this in the settings tab first and the display timeout is only disabled while the player is open.
