### ISSUE TITLE
[BUG] Request time out when going through Tailscale

### ISSUE THREAD

**Issue by nbyakimov** [LeoKlaus/plappa#154]
**Describe the bug**
I've been using Plappa to connect to my ABS instance that's installed on my desktop. When going though the local network I have no problems with sync of the progress or anything. But when using Tailscale sometimes I need to restart Plappa several times before the progress is synced to the correct position. This only happens when I listen to an audiobook on my Desktop and try to sync it on my phone, the other way around this issue is not as defined, it's again slower, but not by as much.

**To Reproduce**
1. Install ABS and Tailscale on Desktop
2. Connect Plappa to ABS from Taiscale installed on the phone
3. Listen to an audiobook and try to sync

**Expected behavior**
To be working as it is on local network 
**Screenshots**
None
**Logs**
Local network

[20.07.2024, 8:47] [CoreDataHandler] Initializing core data store...
[20.07.2024, 8:47] [CoreDataHandler] CoreData store initialized
[20.07.2024, 8:47] [PlaybackStateHandler] Syncing playback states through server
[20.07.2024, 8:47] [StoreKitHandler] unlocked!
[20.07.2024, 8:47] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[20.07.2024, 8:47] [AudioBookShelfAPIHandler] Successfully pushed playbackstates

Tailscale

[20.07.2024, 8:52] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[20.07.2024, 8:52] [JellyfinAPIHandler] Couldn't connect to server: Could not connect to the server.
[20.07.2024, 8:52] [AudioBookShelfAPIHandler] Couldn't connect to server: Could not connect to the server.
[20.07.2024, 8:53] [AudioBookShelfAPIHandler] Couldn't connect to server: The request timed out.
[20.07.2024, 8:53] [AudioBookShelfAPIHandler] Couldn't connect to server: The request timed out.
[20.07.2024, 8:54] [AudioBookShelfAPIHandler] Couldn't connect to server: The request timed out.
[20.07.2024, 8:54] [PlaybackStateHandler] Syncing playback states through server
[20.07.2024, 8:54] [AudioBookShelfAPIHandler] Successfully pushed playbackstates

**Environment(please complete the following information):**
 - Device: iPhone 13 iOS 17.6.1 and Windows 10 22H2 build 19045.4651
 - ABS 2.11.0 and this was on ABS 2.10.0
 - Plappa version 1.3.0

**Additional context**

**Comment by LeoKlaus** [comment]
Thank you for reaching out and for adding the logs!

Generally, the use of VPN shouldn't affect plappa at all, as long as the connection speed and reliability are not affected.

Are you connecting to your server via the IP or the hostname of your pc?

**Comment by nbyakimov** [comment]
In both instances I'm using the IP address either of the local network, or the VPN IP.

**Comment by LeoKlaus** [comment]
> In both instances I'm using the IP address either of the local network, or the VPN IP.

Are those different IPs, i.e. are you logging out and back in every time you switch to the VPN and back?

**Comment by nbyakimov** [comment]
Yes. 

When I connect to the local network logout and connect with the local network IP. When wanting to connect to ABS through Tailscale I logout again and change the IP address to the one from Tailscale. I've done this 2-3 times only, when trying to make Tailscale to work

**Comment by LeoKlaus** [comment]
> Yes.
> 
> When I connect to the local network logout and connect with the local network IP. When wanting to connect to ABS through Tailscale I logout again and change the IP address to the one from Tailscale. I've done this 2-3 times only, when trying to make Tailscale to work

I'm not familiar with Tailscale, but isn't there a way to use the same IP or hostname locally and remotely? A timeout could occur if plappa is trying to connect to a server using the wrong IP (as long as that IP is routable).

I do know that some people use plappa with Tailscale without issues, but those are probably using Linux, not Windows.

**Comment by kgraefe** [comment]
I use the `--advertise-routes` on the tailscale client of the server to forward the local IP onto the tailscale network so that I can use the same address on both networks (via DNS). I don’t have any problems so far. But also I don’t use multiple client, thus this specific issue does not affect me.

**Comment by nbyakimov** [comment]
I tried @kgraefe method and it actually worked! Thank you very much. Now I'm not seeing any drops/timeouts in the logs and the progress is synced fast, to the point that I do not see any difference in the local vs tailscale with `--advertise-routes` option. This can now be closed.

Resolution:

Used `--advertise-routes` option and now I'm connecting with the local network IP to my ABS server with no issues.

**Comment by LeoKlaus** [comment]
Great to hear! Thank you @kgraefe for the input!
