### ISSUE TITLE
[BUG] Progress being synced for deleted audiobooks for audiobookshelf

### ISSUE THREAD

**Issue by fairct** [LeoKlaus/plappa#156]
**Describe the bug**
Audiobooks which have been listened to (or completed) and subsequently deleted from audiobookshelf continue having progress attempted to be synced for them by Plappa. I have not confirmed if this applies to partially completed or only fully completed books.

**To Reproduce**
1. Listen to an audiobook from ABS and allow it to successfully sync.
2. Delete the book from ABS.
3. Book disappears from Plappa as expected
4. Every 10 seconds  logs from ABS indicate that progress is attempted to be synced.

**Expected behavior**
Books which no longer exist on ABS should not have progress synced for them.

**Logs**
Log output from ABS:
```
ERROR [LibraryItem] Library item not found with id "6f6f550d-3956-4d3d-8bf5-a85beb1dbe97"
ERROR [MeController] batchUpdateMediaProgress: Library Item does not exist undefined
```

**Environment:**
 - Device: iPhone12
 - OS: 17.5.1
 - Version 1.3.0
 - ABS 2.11.0

**Additional context**
Deleting the app and reinstalling was sufficient to fix this, but that's kinda heavy to have to do.

**Comment by LeoKlaus** [comment]
Great catch! I've implemented a fix for this, it will release with the next TestFlight and AppStore releases.
