### ISSUE TITLE
[BUG] Sleep Timer is not reset after resume

### ISSUE THREAD

**Issue by uptivuptiz** [LeoKlaus/plappa#157]
**Describe the bug**
The Sleep Timer does not reset when resuming playback, unless the play/pause button in the app is explicitly used.

**To Reproduce**
1. Enable 'Restart Sleep Timer When Resuming' under 'Change Sleep Timer' in Settings.
2. Set a sleep time (ex. 5 min) in the player. Then start playback and let it run out.
3. Use the play/pause button in iOS Control Center or on your headset.
4. Playback resumes, but the Sleep Timer is not Restarted.

**Expected behavior**
Sleep Timer is set to 5 minutes. When it runs out, it should reset to 5 minutes after Play/Pause is pressed via iOS Control Center or the button on a headset. Just like how it works in the Audible app.

**Screenshots**
N/A

**Logs**
N/A

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: 18.0 Beta
 - Version 1.3.0
 - Server Version Emby 4.8.8.0

**Additional context**
N/A

**Comment by LeoKlaus** [comment]
Thank you for reporting this! I've implemented a fix for this. It will release with the next TestFlight and AppStore releases.

**Comment by ckoehler** [comment]
I am experiencing this with the latest version. Resuming with my headset doesn’t reset the sleep timer (set on end of chapter).
