### ISSUE TITLE
[BUG] Simultaneous instead of sequential download

### ISSUE THREAD

**Issue by mrburns-42** [LeoKlaus/plappa#159]
**Describe the bug**
If I have understood the update for the new download system correctly, audiobooks should now be downloaded one after the other and not at the same time (see #111). However, if I want to download two audiobooks, they are downloaded at the same time and not one after the other. If I have misunderstood, the feature request #111 would still be relevant, as the download of simultaneous audiobook files / audiobooks should then be limited.

**To Reproduce**
1. Go to the first audiobook, click on download
2. Go to the second audiobook, click on download
3. Look in the overview of the download manager

**Expected behavior**
That the audiobooks are downloaded one after the other.

**Screenshots**
![IMG_0010](https://github.com/user-attachments/assets/203ffd2a-6ff8-4e26-a102-56a2ae20a867)

**Environment(please complete the following information):**
 - Device: iPad Pro
 - OS: iPadOS 17.4.1
 - Version: 1.4.0 (37)
 - Server Version: ABS 2.11.0

**Comment by LeoKlaus** [comment]
Thank you very much for all your feedback!

This is working as intended, the sequential part is only meant to apply to the individual files within a single book.
Two or three simultaneous downloads shouldn't cause disk thrashing on HDDs and parallel downloads tend to make better use of the available bandwidth.

If you feel like there should be a general queue for downloads or a limit for simultaneous downloads anyway, feel free to reopen this as a feature request.

**Comment by mrburns-42** [comment]
Okay, that makes sense with the hard disk problem. I had actually misunderstood that.

I will open a feature request later, as I think it would make sense to be able to set how many audiobooks are loaded at the same time. But more on that later in the feature request.
