### ISSUE TITLE
[BUG] Rewinding does not work at the beginning of an audiobook

### ISSUE THREAD

**Issue by mrburns-42** [LeoKlaus/plappa#161]
**Describe the bug**
My rewind is set to 15 seconds. Rewinding is not possible within the first 14 seconds of the audiobook. When I press the rewind button, nothing happens.

**To Reproduce**
1. Go to an new audiobook.
2. Click on start.
3. Click on rewind in the first 15 seconds.
4. See error.

**Expected behavior**
With the setting of 15 seconds rewind time, I expect the first 14 seconds of the audiobook to jump back to seconds 0 when the rewind button is pressed.

**Screenshots**
![IMG_7658](https://github.com/user-attachments/assets/2ef3b540-169d-415e-b6b6-c7b3f8af9998)

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.5.1
 - Version: 1.4.0 (39)
 - Server Version: ABS 2.12.1

**Comment by LeoKlaus** [comment]
I've just implemented a fix for this, it will release with the next AppStore and TestFlight updates.
