### ISSUE TITLE
[BUG] Playback pauses when moving to background

### ISSUE THREAD

**Issue by prince-modi** [LeoKlaus/plappa#165]
**Describe the bug**
When minimizing the app with something playing, 50% of the time the playback stops. The ui doesn't change switching back to the app. Resuming again and minimizing doesn't stop the playback then.

**To Reproduce**
1. Open the app and play anything.
2. Minimize the app.

**Expected behavior**
Continuous playback.

**Environment(please complete the following information):**
 - Device: iPhone 11 Pro and M1 iPad Pro
 - OS: iOS 17.5.1 and iPad OS 17.5.1
 - Version: plappa 1.3.0
 - Server Version: AudioBookShelf 2.11.0

**Comment by LeoKlaus** [comment]
Thank you for reaching out!

This issue has been fixed in a recent TestFlight update. You can join the TestFlight beta here: https://testflight.apple.com/join/oSAekRD5

The update should release to the AppStore fairly soon.

**Comment by prince-modi** [comment]
Ohh okay. That's great!

**Comment by LeoKlaus** [comment]
I think this can be closed, let me know if this happens again!
