### ISSUE TITLE
[BUG] Long press on "Recently Added" or "Listen Again" select first item on list (v1.4.0 42)

### ISSUE THREAD

**Issue by stickystyle** [LeoKlaus/plappa#166]
**Describe the bug**
Wrong item is selected when long pressing on "Recently Added" or "Listen Again" row

**To Reproduce**
Long press on an item in the "Recently Added" or "Listen Again" row, and observe the first item on the list is selected instead of the one you pressed on.

**Environment(please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 18 Beta
 - Server Version ABS 2.12.1

https://github.com/user-attachments/assets/e487ffcf-9d36-42c2-85c6-bfceeaa558fc

**Comment by LeoKlaus** [comment]
I just implemented a fix, it will release to TestFlight shortly.
