### ISSUE TITLE
[BUG] Ebooks mistaken as audiobooks, causing crashes. 

### ISSUE THREAD

**Issue by IshmaelObeso** [LeoKlaus/plappa#167]
**Describe the bug**
If there are ebooks on your ABS server, the app will recognize them as audiobooks. It will allow you to attempt to play or download, but will crash or give errors when anything is attempted. Furthermore, if you remove the ebooks from your ABS server the app will get stuck in a crash loop until you reinstall. 

**To Reproduce**
1. Download ebook to ABS server
2. Select ebook in app (displayed as audiobook)
3. Attempt to play/download
4. Remove ebook from server 
5. Try to open app

**Expected behavior**
App recognizes ebooks as ebooks and does not display them, or simply does not allow attempts to play/download. 

**Screenshots**

![IMG_4809](https://github.com/user-attachments/assets/50e1e2c1-8e5a-4766-b3f1-e8bf4ed652db)
![IMG_4808](https://github.com/user-attachments/assets/94be56bb-ac3a-49bc-a31f-6df5f51e4e9e)

**Logs**
If applicable, add logs from plappa (Settings->Get Debug Logs) or Jellyfin (Dashboard->Advanced->Logs).

**Environment(please complete the following information):**
 - Device: [e.g. iPhone15]

**Additional context**

**Comment by LeoKlaus** [comment]
Thank you for reporting this! I've just implemented a fix for this, it will release with the next updates to TestFlight and the AppStore.
