### ISSUE TITLE
[BUG] Option to select the library in car play

### ISSUE THREAD

**Issue by h4wwk3ye** [LeoKlaus/plappa#169]
**Describe the bug**
In carplay all the books from all the libraries are shown. I have different libraries for epub and different for audiobooks. Car play shows all the books.

**Expected behavior**
Option to select the library so books that both epubs and audiobooks are not shown

**Environment(please complete the following information):**
 - Device: [e.g. iPhone6] Iphone 15 pro
 - OS: [e.g. iOS8.1] iOS 17.6.1
 - Version [e.g. 22] 43
 - Server Version [e.g. Jellyfin 10.8.13] Audiobookshelf 2.12.3

**Comment by LeoKlaus** [comment]
Hey Farhan, thank you for reporting this!

It's not really a bug, the CarPlay interface is designed to be as simple as possible and should allow users to resume their latest podcasts or audiobooks regardless of the library they're in.

I see how this is very counterproductive in your case, though. The upcoming 1.4.0 update of plappa will stop showing ebooks at all, as those are not supported as of now. Would this fix your issue or do you think a dedicated library switcher in CarPlay would be better?

**Comment by h4wwk3ye** [comment]
Either solution works for me. I do have a different library for podcasts, but I don't really use that.
~~I am also facing another issue where the cover of one of the audiobooks is not correct. I'm not really sure how the car play interface is picking that cover, as the iPhone app shows the same cover as Audiobookshelf.~~

Edit: Ignore the other issue I mentioned above. Was some caching issue. Logged out and logged in again from the server in the app, and it now shows the correct cover.

**Comment by LeoKlaus** [comment]
The 1.4.0 update is live on the AppStore now, so I'm closing this. If you still see unwanted items in CarPlay, feel free to reopen.
