### ISSUE TITLE
[BUG] OPUS file not working

### ISSUE THREAD

**Issue by arjunvenk** [LeoKlaus/plappa#170]
**Describe the bug**
I am not able to play opus files from my audiobookshelf via plappa. 

The same file works via ABS web interface and I am able to play other formats from the same ABS server via plappa. 
So I know the opus file is okay and my server/plappa are okay.

I thought maybe iOS just couldn't handle OPUS but I see in your 1.3 update you mentioned you fixed OPUS. Thanks!

**Logs**
[8/12/2024, 10:17 AM] [CoreDataHandler] Initializing core data store...
[8/12/2024, 10:17 AM] [CoreDataHandler] CoreData store initialized
[8/12/2024, 10:17 AM] [PlaybackStateHandler] Syncing playback states through server
[8/12/2024, 10:17 AM] [ReadingListHandler] Found no objects in reading list
[8/12/2024, 10:17 AM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[8/12/2024, 10:17 AM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[8/12/2024, 10:17 AM] [SoundHandler] Tried to play an invalid asset with URL: https://CENSORED.CENSORED.com/api/items/69705b4a-ceba-4391-8b11-48d954c15d06/file/649362782082534039/download
[8/12/2024, 10:17 AM] [SoundHandler] Additional information:
Title: The Fellowship of the Ring
ID: 69705b4a-ceba-4391-8b11-48d954c15d06
Number of chapters: 24
[8/12/2024, 10:17 AM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates

**Environment(please complete the following information):**
 - Device: iPhone 15 pro max
 - OS:  iOS 18.1 dev beta
 - Version 1.3.0 (I tried to update to 1.4 but it doesnt seem to be pushed to me yet)
 - Server Version ABS 2.11

**Comment by LeoKlaus** [comment]
Thank you for reporting this!

I don't have any opus files on my server, so I just downloaded some random samples to test when fixing #130.

Can you give me some more information on the file you're trying to play (like bitrate, codec, file size, channels and so on)?
Plappa uses the default AVPlayer from iOS which is generally fairly robust, but this might as well be a limitation of the player.

The fix for that issue was related to the metadata from ABS, but that seems to load correctly in your case.

**Comment by arjunvenk** [comment]
<img width="702" alt="SCR-20240812-mgoj" src="https://github.com/user-attachments/assets/16286b78-9dc1-4fa5-b45f-7c0da3d57ce9">
[fellowship probetext.txt](https://github.com/user-attachments/files/16590153/fellowship.probetext.txt)

Here you go! I can also share the file with you privately via Drive or something if you want.

**Comment by arjunvenk** [comment]
[fellowship probetext.txt](https://github.com/user-attachments/files/16590170/fellowship.probetext.txt)

This didnt seem to attach last time. I'll try again

**Comment by LeoKlaus** [comment]
Thank you for the additional info and sorry for the late response.

As expected, iOS's AVPlayer is unable to decode the ogg format, so it won't direct play. For now, plappa doesn't have the ability to request transcoded files via ABS, so your best bet would be to convert the file.

Luckily, ABS can do that right from the WebUI, using the "tools" section when editing that audiobooks metadata.

I'm closing this issue for now as support for OGG is not something I plan to implement. I may add support for transcodes in a future update, but I think that should be a separate feature request.
