### ISSUE TITLE
[BUG] Ghost Libaries

### ISSUE THREAD

**Issue by desoare** [LeoKlaus/plappa#178]
**Describe the bug**
Removed libraries are still showing under the select library menu. When selected ghost items (audiobooks) shows with cover and comments etc.

**To Reproduce**
in Home selecting the library selector.

**Expected behavior**
show only the current libraries.

**Screenshots**

**Logs**
If applicable, add logs from plappa (Settings->Get Debug Logs) or Jellyfin (Dashboard->Advanced->Logs).

**Environment(please complete the following information):**
 - Device: iphone 14 pro max
 - OS: [e.g. iOS17.6
 - Server Version audiobookshelf latest

**Additional context**

**Comment by LeoKlaus** [comment]
Thank you for reporting this! I've just implemented a fix. It will release with the next update.
