### ISSUE TITLE
[BUG] Will not load libraries on new instance

### ISSUE THREAD

**Issue by asc6** [LeoKlaus/plappa#181]
**Describe the bug**
I have recently created an ABS server and while the server itself works fine, the plappa app will not load a library or anything.

**To Reproduce**
1. Create brand new ABS server
2. Download app
3. Login (I'm using OIDC)
4. App changes screens to show Library and Settings tab
5. App is stuck spinning

**Expected behavior**
App loads and connects to ABS showing a library 

**Screenshots**
![IMG_4585](https://github.com/user-attachments/assets/c7c2a618-797a-4e8a-9fd5-2595b08cf44e)

**Logs**

> [9/3/2024, 7:55 AM] [plappa] Encountered an error while decoding libraries: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "skipMatchingMediaWithAsin", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "libraries", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "settings", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"skipMatchingMediaWithAsin\", intValue: nil) (\"skipMatchingMediaWithAsin\").", underlyingError: nil))
[9/3/2024, 7:55 AM] [plappa] Encountered an unexpected error error while loading libraries: The operation couldn’t be completed. (plappa.APIError error 1.)
unexpected
[9/3/2024, 7:55 AM] [plappa] Encountered an error while decoding libraries: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "skipMatchingMediaWithAsin", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "libraries", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "settings", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"skipMatchingMediaWithAsin\", intValue: nil) (\"skipMatchingMediaWithAsin\").", underlyingError: nil))
[9/3/2024, 7:55 AM] [plappa] Encountered an unexpected error error while loading libraries: The operation couldn’t be completed. (plappa.APIError error 1.)
unexpected
[9/3/2024, 8:06 AM] [AudioBookShelfAPIHandler] Successfully posted sessions
[9/3/2024, 8:06 AM] [plappa] Encountered an error while decoding libraries: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "skipMatchingMediaWithAsin", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "libraries", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "settings", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"skipMatchingMediaWithAsin\", intValue: nil) (\"skipMatchingMediaWithAsin\").", underlyingError: nil))
[9/3/2024, 8:06 AM] [plappa] Encountered an unexpected error error while loading libraries: The operation couldn’t be completed. (plappa.APIError error 1.)
unexpected
[9/3/2024, 8:06 AM] [plappa] Encountered an error while decoding libraries: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "skipMatchingMediaWithAsin", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "libraries", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "settings", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"skipMatchingMediaWithAsin\", intValue: nil) (\"skipMatchingMediaWithAsin\").", underlyingError: nil))
[9/3/2024, 8:06 AM] [plappa] Encountered an unexpected error error while loading libraries: The operation couldn’t be completed. (plappa.APIError error 1.)
unexpected

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: 17.6.1
 - Version: Both App store (1.4.0) and TestFlight (1.4.2 (49)) are showing the same error in the debug log
 - Server Version: Audiobookshelf v2.13.3 (docker install)

**Additional context**
Based on the debug log I assumed it might be because it's a new library so I flipped the setting for ASIN on and it gave the same error about ISBN which is the next option in the ABS settings. Flipping ASIN back off gets me back the same error. This seems similar to #172 so I downloaded the TestFlight version, but had the exact same result. Thanks for your time!

**Comment by LeoKlaus** [comment]
Whoops, didn't mean to close this already. I just implemented a fix, it's in TestFlight only for now (1.4.1 build 50).
Let me know if that worked :)

**Comment by asc6** [comment]
Works like a charm. Everything synced up and it plays files as expected. Thanks, that was super quick!

**Comment by LeoKlaus** [comment]
Thank you very much for the update!
The fix is now live on the AppStore as well, so I'll close this.
