### ISSUE TITLE
[BUG] Playback stops or mutes when using navigation with google maps.

### ISSUE THREAD

**Issue by hentoe** [LeoKlaus/plappa#187]
**Describe the bug**
Playback stops or is muted, when navigating with Google Maps.

**To Reproduce**
1. Connect Bluetooth Headphones
2. Go to Google Maps, start navigation
4. Go back to plappa, start playback
5. Return to Google maps
6. Playback stops
7. Go to Control Center
8. Muted playback
9. Go to plappa, start playback 
10. playback stops

**Expected behavior**
I would expect the app to keep playing, like with other audio player apps.

**Environment:**
 - Device: iPhone14
 - OS: iOS17.6.1
 - Server Version: Audiobookshelf 2.12.3
 - Headphones: Air Pods Pro (1)

**Comment by hentoe** [comment]
Restarted the app. Can't reproduce now.

**Comment by LeoKlaus** [comment]
> Restarted the app. Can't reproduce now.

Thanks for the update. Feel free to reopen if this happens again.

I've seen some reports of intermittent issues with background playback, but have yet to find a way to reproduce this on any of my devices.
