### ISSUE TITLE
[BUG] Cannot log in on latest version of ABS (2.13.4)

### ISSUE THREAD

**Issue by thedualspace** [LeoKlaus/plappa#189]
**Describe the bug**
I updated to the latest version of Audiobookshelf (2.13.4), and I now cannot log in. 

**To Reproduce**
1. Open App
2. Select Audiobookshelf, enter credentials

**Expected behavior**
Log in successfully

**Screenshots**
![photo_2024-09-12_11-10-10](https://github.com/user-attachments/assets/dc7e3288-bcc4-47a5-b995-bf2ea3b97e08)

**Logs**
```
[12/9/2024, 10:55] [AudioBookShelfAPIHandler] Tried to init ABS APIHandler with no valid token in keychain
[12/9/2024, 10:55] [AudioBookShelfAPIHandler] Keychain error: plappa.KeychainError.credentialsNotFound
[12/9/2024, 10:55] [CoreDataHandler] Initializing core data store...
[12/9/2024, 10:55] [CoreDataHandler] CoreData store initialized
[12/9/2024, 10:55] [JellyfinAPIHandler] Couldn't connect to server: Could not connect to the server.
[12/9/2024, 10:55] [JellyfinAPIHandler] Couldn't connect to server: Could not connect to the server.
[12/9/2024, 10:55] [AudioBookShelfAPIHandler] Couldn't connect to server: Could not connect to the server.
[12/9/2024, 10:55] [plappa] Encountered an error while decoding status response: The data couldn’t be read because it isn’t in the correct format.
dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character '<' around line 1, column 1." UserInfo={NSDebugDescription=Unexpected character '<' around line 1, column 1., NSJSONSerializationErrorIndex=0})))
[12/9/2024, 10:55] [AudioBookShelfAPIHandler] Server returned unexpected response:
<private>
```

**Environment(please complete the following information):**
 - iPhone 12
 - iOS 17.5.1
 - Plappa Version: 1,4.3 (52) Testflight
 - Server Version ABS 2.13.4

**Additional context**
Log in also seems not to be working on ShelfPlayer. I can log in successfully in the browser.

**Comment by LeoKlaus** [comment]
That's curious, can you check what response you get, when you
`curl http://[ip-of-your-server]:[port]/status`?

Login works fine on my instance using 2.13.4.

The response should be a JSON looking something like this:
```json
{
    "app": "audiobookshelf",
    "serverVersion": "2.13.4",
    "isInit": true,
    "language": "en-us",
    "authMethods": [
        "local",
        "openid"
    ],
    "authFormData": {
        "authLoginCustomMessage": null,
        "authOpenIDButtonText": "Login with OpenId",
        "authOpenIDAutoLaunch": false
    }
}
```

The logs look like your server is returning HTML (judging by the first character being `<`), but the response isn't logged properly (or is empty):
`[12/9/2024, 10:55] [AudioBookShelfAPIHandler] Server returned unexpected response:`

**Comment by thedualspace** [comment]
Response is :

```
{
    "app": "audiobookshelf",
    "serverVersion": "2.13.4",
    "isInit": true,
    "language": "en-us",
    "authMethods": [
        "local"
    ],
    "authFormData": {
        "authLoginCustomMessage": null
    }
}
```

**Comment by LeoKlaus** [comment]
Looks fine, can you check if logging in with another user works?

**Comment by thedualspace** [comment]
It also fails to login with a new Test user, with the same error in the app.

Logging in with Postman returns what looks like a valid response:

```
{
    "user": {
        "id": "snip",
        "username": "Test",
        "email": null,
        "type": "user",
        "token": "snip",
        "mediaProgress": [],
        "seriesHideFromContinueListening": [],
        "bookmarks": [],
        "isActive": true,
        "isLocked": false,
        "lastSeen": null,
        "createdAt": 1726137552099,
        "permissions": {
            "download": true,
            "update": false,
            "delete": false,
            "upload": false,
            "accessAllLibraries": true,
            "accessAllTags": true,
            "accessExplicitContent": true,
            "selectedTagsNotAccessible": false
        },
        "librariesAccessible": [],
        "itemTagsSelected": [],
        "hasOpenIDLink": false
    },
    "userDefaultLibraryId": "snip",
    "serverSettings": {
        "id": "server-settings",
        "scannerFindCovers": true,
        "scannerCoverProvider": "google",
        "scannerParseSubtitle": false,
        "scannerPreferMatchedMetadata": false,
        "scannerDisableWatcher": false,
        "storeCoverWithItem": false,
        "storeMetadataWithItem": false,
        "metadataFileFormat": "json",
        "rateLimitLoginRequests": 10,
        "rateLimitLoginWindow": 600000,
        "backupPath": "/metadata/backups",
        "backupSchedule": false,
        "backupsToKeep": 2,
        "maxBackupSize": 1,
        "loggerDailyLogsToKeep": 7,
        "loggerScannerLogsToKeep": 2,
        "homeBookshelfView": 1,
        "bookshelfView": 1,
        "podcastEpisodeSchedule": "0 * * * *",
        "sortingIgnorePrefix": false,
        "sortingPrefixes": [
            "the",
            "a"
        ],
        "chromecastEnabled": false,
        "dateFormat": "dd/MM/yyyy",
        "timeFormat": "HH:mm",
        "language": "en-us",
        "logLevel": 2,
        "version": "2.13.4",
        "buildNumber": 1,
        "authLoginCustomMessage": null,
        "authActiveAuthMethods": [
            "local"
        ],
        "authOpenIDIssuerURL": null,
        "authOpenIDAuthorizationURL": null,
        "authOpenIDTokenURL": null,
        "authOpenIDUserInfoURL": null,
        "authOpenIDJwksURL": null,
        "authOpenIDLogoutURL": null,
        "authOpenIDTokenSigningAlgorithm": "RS256",
        "authOpenIDButtonText": "Login with OpenId",
        "authOpenIDAutoLaunch": false,
        "authOpenIDAutoRegister": false,
        "authOpenIDMatchExistingBy": null
    },
    "ereaderDevices": [],
    "Source": "docker"
}
```

**Comment by thedualspace** [comment]
I am using Wireguard, though this worked without issue before I updated, and all my other services are working fine.

I have updated the logs in my original post, markdown parsing removed the response from the server that plappa is reporting: "`<private>`".

Still, I dont get that response in postman

**Comment by thedualspace** [comment]
I have updated the logs, markdown parsing removed the response from the server that plappa is reporting: "<private>".

Still, I dont get that response in postman

**Comment by thedualspace** [comment]
Okay I got it to return HTML. I am now running postman on a laptop using a wireguard tunnel, like my phone is.

When I make the request on the local machine running the server, I get the JSON as expected.

When I make the request on machines running Wireguard, ABS sends a different response for some reason? 
Note I can still access the service in my browser on both devices just fine, login works.

```
<!doctype html>
<html lang="en" data-n-head="%7B%22lang%22:%7B%221%22:%22en%22%7D%7D">

<head>
	<meta data-n-head="1" charset="utf-8">
	<meta data-n-head="1" name="viewport" content="width=device-width,initial-scale=1">
	<meta data-n-head="1" data-hid="description" name="description" content="">
	<meta data-n-head="1" data-hid="robots" name="robots" content="noindex">
	<meta data-n-head="1" data-hid="charset" charset="utf-8">
	<meta data-n-head="1" data-hid="mobile-web-app-capable" name="mobile-web-app-capable" content="yes">
	<meta data-n-head="1" data-hid="apple-mobile-web-app-capable" name="apple-mobile-web-app-capable" content="yes">
	<meta data-n-head="1" data-hid="apple-mobile-web-app-status-bar-style" name="apple-mobile-web-app-status-bar-style"
		content="black">
	<meta data-n-head="1" data-hid="apple-mobile-web-app-title" name="apple-mobile-web-app-title"
		content="Audiobookshelf">
	<meta data-n-head="1" data-hid="theme-color" name="theme-color" content="#232323">
	<meta data-n-head="1" data-hid="og:type" name="og:type" property="og:type" content="website">
	<meta data-n-head="1" data-hid="og:title" name="og:title" property="og:title" content="Audiobookshelf">
	<meta data-n-head="1" data-hid="og:site_name" name="og:site_name" property="og:site_name" content="Audiobookshelf">
	<title>Audiobookshelf</title>
	<link data-n-head="1" rel="icon" type="image/x-icon" href="/favicon.ico">
	<link data-n-head="1" rel="apple-touch-icon" href="/ios_icon.png">
	<link data-n-head="1" data-hid="shortcut-icon" rel="shortcut icon" href="/icon.svg">
	<link data-n-head="1" data-hid="apple-touch-icon" rel="apple-touch-icon" href="/icon192.png" sizes="any">
	<link data-n-head="1" rel="manifest" href="/_nuxt/manifest.aafd1341.json" data-hid="manifest">
	<base href="/">
	<link rel="preload" href="/_nuxt/9e643ba.js" as="script">
	<link rel="preload" href="/_nuxt/5625f5c.js" as="script">
	<link rel="preload" href="/_nuxt/a873ead.js" as="script">
	<link rel="preload" href="/_nuxt/41b60f2.js" as="script">
</head>

<body>
	<div id="__nuxt">
		<style>
			#nuxt-loading {
				background: #fff;
				visibility: hidden;
				opacity: 0;
				position: absolute;
				left: 0;
				right: 0;
				top: 0;
				bottom: 0;
				display: flex;
				justify-content: center;
				align-items: center;
				flex-direction: column;
				animation: nuxtLoadingIn 10s ease;
				-webkit-animation: nuxtLoadingIn 10s ease;
				animation-fill-mode: forwards;
				overflow: hidden
			}

			@keyframes nuxtLoadingIn {
				0% {
					visibility: hidden;
					opacity: 0
				}

				20% {
					visibility: visible;
					opacity: 0
				}

				100% {
					visibility: visible;
					opacity: 1
				}
			}

			@-webkit-keyframes nuxtLoadingIn {
				0% {
					visibility: hidden;
					opacity: 0
				}

				20% {
					visibility: visible;
					opacity: 0
				}

				100% {
					visibility: visible;
					opacity: 1
				}
			}

			#nuxt-loading>div,
			#nuxt-loading>div:after {
				border-radius: 50%;
				width: 5rem;
				height: 5rem
			}

			#nuxt-loading>div {
				font-size: 10px;
				position: relative;
				text-indent: -9999em;
				border: .5rem solid #f5f5f5;
				border-left: .5rem solid #000;
				-webkit-transform: translateZ(0);
				-ms-transform: translateZ(0);
				transform: translateZ(0);
				-webkit-animation: nuxtLoading 1.1s infinite linear;
				animation: nuxtLoading 1.1s infinite linear
			}

			#nuxt-loading.error>div {
				border-left: .5rem solid #ff4500;
				animation-duration: 5s
			}

			@-webkit-keyframes nuxtLoading {
				0% {
					-webkit-transform: rotate(0);
					transform: rotate(0)
				}

				100% {
					-webkit-transform: rotate(360deg);
					transform: rotate(360deg)
				}
			}

			@keyframes nuxtLoading {
				0% {
					-webkit-transform: rotate(0);
					transform: rotate(0)
				}

				100% {
					-webkit-transform: rotate(360deg);
					transform: rotate(360deg)
				}
			}
		</style>
		<script>
			window.addEventListener("error",function(){var e=document.getElementById("nuxt-loading");e&&(e.className+=" error")})
		</script>
		<div id="nuxt-loading" aria-live="polite" role="status">
			<div>Loading...</div>
		</div>
	</div>
	<script>
		window.__NUXT__={config:{version:"2.13.4",routerBasePath:"",_app:{basePath:"/",assetsPath:"/_nuxt/",cdnURL:null}}}
	</script>
	<script src="/_nuxt/9e643ba.js"></script>
	<script src="/_nuxt/5625f5c.js"></script>
	<script src="/_nuxt/a873ead.js"></script>
	<script src="/_nuxt/41b60f2.js"></script>
</body>

</html>
```

**Comment by LeoKlaus** [comment]
Thank you a lot for all the updates!
That's weird, I don't see how Wireguard could cause this. Anything in the ABS server logs?

**Comment by thedualspace** [comment]
Nevermind I used GET instead of POST.. Silly mistake.

The server is returning JSON correctly when I POST to /login correctly, on all devices.

ABS logs show logins when using Postman, as expected. When attempting to log in with Plappa, nothing is displayed in the ABS logs

After a restart, I can now log in with Shelfplayer, but not Plappa. I'm struggling to make any sense of this.

**Comment by thedualspace** [comment]
Ok I have logged in now. I added the port number manually and the log-in was successful!

That was a mistake on my part, though I think it would be good to indicate in the UI if a port has been left out, that it needs to be added manually.

There is also room for better error handling in the case of failed logins in general I think.

When I try log in with the new test user I made, it still fails with the error I mentioned in my original post, but with very little info why even in the logs  

Aaand now the test user is working also, after force closing the app a few times. 

This has been a bizarre turn of events. 

Thanks for your help

**Comment by justcallmelarry** [comment]
> That was a mistake on my part, though I think it would be good to indicate in the UI if a port has been left out, that it needs to be added manually.

I think this is hard to do without making assumptions 🤔 I run my server behind a reverse proxy, so I do not need to specify a port… on http (rather than https) it's a bit trickier, though, but if you are running the server bare metal (rather than in docker)  you also do not need to manually add a port, as 80 is default if none is specified. So it wouldn't be "correct" to have a warning or w/e for a missing port.

I could see that you have a placeholder text for the http option that also includes the port, to give you a hint that it should be included… or something like that.

**Comment by thedualspace** [comment]
Placeholder text could be helpful definitely, good shout. I was imagining that with a failed login that you are prompted with a general failure message that includes common mistakes. Something like:

"Unexpected response from server: Please check the IP address and port number and try again"

when http is used. What do you think?

**Comment by LeoKlaus** [comment]
> I think it would be good to indicate in the UI if a port has been left out, that it needs to be added manually.

I agree with Lauri (Larry?) here, it's hard to provide a meaningful warning as ABS could run on any port and I would be pretty annoyed if I had to specify :443 every time I log into my instance.

> There is also room for better error handling in the case of failed logins in general I think.

I absolutely agree. The (lack of) error handling often makes troubleshooting difficult. And I think a general help message like you proposed would be a great addition!

> When I try log in with the new test user I made, it still fails with the error I mentioned in my original post, but with very little info why even in the logs
> 
> Aaand now the test user is working also, after force closing the app a few times.

I've seen issues like that a few times now, seems like the URLSession can get stuck in an error state sometimes and just refuse to work until the app is force closed. This most notably happens when a user initially denies local network access, requiring a reboot of the entire device to make network access work again.

**Comment by LeoKlaus** [comment]
I've now added some better logging for errors like this and a little help text. I'll close this issue now, thank you for the feedback!

**Comment by justcallmelarry** [comment]
> I agree with Lauri (Larry?) here

Both are fine :)
