### ISSUE TITLE
Update chapter metadata

### ISSUE THREAD

**Issue by sevenlayercookie** [LeoKlaus/plappa#190]
Related to:   https://github.com/LeoKlaus/plappa/issues/147#issuecomment-2216901032_
            
 When refreshing book by dragging down, chapter information is not updated. I updated chapter information (chapter timestamps and names) for a book and I cannot get Plappa to update to the new chapter information.

**Comment by LeoKlaus** [comment]
Thank you for reporting this! I've just released 1.4.3 build 55 to fix this issue.
