### ISSUE TITLE
Feature Request: iOS 15 Support

### ISSUE THREAD

**Issue by JadoJodo** [LeoKlaus/plappa#193]
I know this is a big ask, but iOS 15 is the last version that the iPod Touch supports. I was hoping to setup Plappa for my daughter on her iPod Touch, but it seems Plappa is 16+. Is there any way this could be enabled for iOS 15 support?

Thank you!

**Comment by LeoKlaus** [comment]
Hey Jordan,

I'm afraid that's pretty much impossible. Plappa is built in SwiftUI and the entire navigation is built around NavigationSplitView and NavigationStack, which Apple didn't port back to iOS 15 (along with a ton of other stuff plappa relies on).

I've tried to get around this but it would basically require rewriting the entire interface and even parts of the backend for iOS 15.

I don't know if the official ABS app supports iOS 15, you might want to try that.

**Comment by JadoJodo** [comment]
Thank you! Love the app!
