### ISSUE TITLE
[Feature Request] Please add the .opus extension support!

### ISSUE THREAD

**Issue by spartan15** [LeoKlaus/plappa#199]
Hi!
When I try to play an opus file in plappa from my Jellyfin server, it doesn't start. It would be nice to have the opus support.

Thank you!

**Comment by ebb-earl-co** [comment]
@spartan15 if you take a look at the [Jellyfin audio compatibility](https://jellyfin.org/docs/general/clients/codec-support/), you’ll see that iOS doesn’t support OPUS audio except for .caf files.

It is certainly _possible_ for @LeoKlaus to implement a workaround, but I expect that to be a big lift…

**Comment by LeoKlaus** [comment]
Hey spartan15, thank you for reaching out!

As @ebb-earl-co noted, OGG sadly isn’t supported in iOSs native AVPlayer (as discussed in #170) and I don’t plan to ever switch to a third party framework for handling audio.

This pretty much means that most .opus files will not play in plappa. The simplest workaround is to re-encode these files to a more broadly supported format like MP3 or M4B.
