### ISSUE TITLE
[feature] default bookmark name to date and time if empty

### ISSUE THREAD

**Issue by cowens** [LeoKlaus/plappa#201]
While driving across the country, I will hit the bookmark button regularly so if something on the road distracts me I can hop back to a place I know in the story. It is dangerous to try to enter text while driving, so I would like to be able to just hit the bookmark button and have the bookmark name be the date and time the button was pressed or (less desirable because it requires more attention) be able to hit the bookmark button, hit ok, and have it set the name to the current date and time (rather than doing nothing as it currently does).

Making the behavior of the bookmark button configurable in settings would be nice, but I understand that can lead to code complexity and a confusing/daunting configuration section.

**Comment by mrburns-42** [comment]
There is already a feature request: https://github.com/LeoKlaus/plappa/discussions/96

You can thumb up the feature request, to vote for them.

**Comment by LeoKlaus** [comment]
Hey cowens, thank you for the suggestion! As mrburns noted, there's already an open feature request for this in discussions, so I'll close this for now.
