### ISSUE TITLE
[BUG] Save me from my stupidity - remember where we were per/chapter

### ISSUE THREAD

**Issue by jeeftor** [LeoKlaus/plappa#204]
**Describe the bug**

I've run into a few situations where I've accidentally jumped to the beginning of the book. Is there a way to maintain the "last position" in each chapter - so if I make a mistake - at least I can easily get back to where I was?

(Feature request not bug report)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add logs from plappa (Settings->Get Debug Logs) or Jellyfin (Dashboard->Advanced->Logs).

**Environment(please complete the following information):**
 - Server Version [e.g. Jellyfin 10.8.13]

**Additional context**

**Comment by LeoKlaus** [comment]
Hey Jeef,

thank you for reaching out! While I understand your request, I don't think it's possible to build in a way that makes sense.
If you saved the position for every chapter, you would quickly end up with conflicting data (i.e. where to resume when multiple chapters are played only half-way?).

The quickest way to resolve the issue your describing might be to check the history tab: 
![image](https://github.com/user-attachments/assets/7d9e9b14-d5f9-471d-80ae-92fa6e6bfdac)

It will show all playback sessions for that book, the start and end times are clickable links that jump directly to that position.
