### ISSUE TITLE
[BUG] Playback speed does not stick after app closes

### ISSUE THREAD

**Issue by th0mcat** [LeoKlaus/plappa#26]
**Describe the bug**
Playback speed does not stick after app closes

**To Reproduce**
1. Open app and select book
2. Change playback speed
3. Close app
4. Reopen app and select same book

**Expected behavior**
Playback speed sticks when app closes

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: 17.4.1
 - Version: 1.1.0
 - Server Version: Audiobookshelf 2.8.1

**Comment by LeoKlaus** [comment]
Good call, should be an easy fix.

**Comment by LeoKlaus** [comment]
I've changed this with update 1.1.1, it should release in the coming days.
