### ISSUE TITLE
[BUG]  close icon on debug logs not working

### ISSUE THREAD

**Issue by mutschler** [LeoKlaus/plappa#28]
**Describe the bug**
Logs can't be closed by clicking the icon only by swiping down

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Get Debug Log'
3. Click on Close icon in left corner

**Expected behavior**
Closing of the dialog

**Environment(please complete the following information):**
 - Device: iPhoneX
 - OS: 16
 - Version 1.1.0
 - Server Version: AudioBookshelf 2.8.1

**Comment by LeoKlaus** [comment]
Good catch, will fix this!
