### ISSUE TITLE
[BUG] Tapping a Book won't start Playback

### ISSUE THREAD

**Issue by mutschler** [LeoKlaus/plappa#31]
**Describe the bug**
Single tapping a book will not start Playback you have to long tap it to bring up the menu and select listen.

**Expected behavior**
I'd expect on single tapping the book to play it

**Environment(please complete the following information):**
 - Device: iPhoneX
 - OS: 16
 - Version 1.1.0
 - Server Version: AudioBookshelf 2.8.1

**Comment by LeoKlaus** [comment]
I assume you're talking about any of the lists of books? I felt like that might be a bit unintuitive, but I don't see why I shouldn't just give you an option to select the preferred behavior.

**Comment by mutschler** [comment]
Yes i was Talking Abluft any of the list views. 

I just checked a few other apps and how those handle tapping on media items and while i can understand your concern about it being unintuitive to start playaback by tapping it I do think tapping should do at least anything. Currently it just does nothing which feels kinda weird tbh. 

Here are some ideas what could happen when tapping the entry:

- Download the file if not already downloaded
- Start playback if the file is downloaded
- Open the detail view (currently there is no way to check metadata like series, etc)

Depending on which App you'll look at most of them implement one of that functions on click and have more options behind a sheet coming up when long-pressing or hitting the "more" icon.

BTW: is there currently a way to get details of an entry? Like description, series etc? If not I'd love to have that option as well!

**Comment by mutschler** [comment]
Holy... that's some weird behaviour... i found out what confused me!
Just found out that there is already a implementation on single tap... just not consistent everywhere!

I'd like to change my report:

Please make it so tapping the Element from enywhere opens the Detail page. Currently that only works in the special occasion:

1. Go to Home View
2. Click any of the Headlines ("where you...", "recentyl added" etc)
3. Click a book and see detail view

Now try this:

1. Go to Home View or Books
2. Click Book
3. Nothing happens

so where it works as i would expect it to:
- Any of the Subviews of the Home view ("recently added" etc)
- Inside a collection
- From Authors view


where it doesn't:
- Home view
- Books view

Maybe the video makes it more clear:
https://github.com/LeoKlaus/plappa/assets/18465333/57794bbf-651a-4a44-ac58-e984bcb86840

**Comment by LeoKlaus** [comment]
I'm slowly getting the impression that there's something very weird going on in your case, this is how interaction with the list of books should work:

https://github.com/LeoKlaus/plappa/assets/66492595/a7237875-c6bc-43b3-a74d-d3913eab6fc5


If it doesn't work that way on your device, that's a bug and very much not how plappa is intended to work :D

**Comment by LeoKlaus** [comment]
Okay, I see we found the issue!

That's curious. As you can see in the video I posted, the books in the list are indeed tappable and do exactly what you want them to. I wonder if iOS 16 is to blame for this. You're the only person that has reported this so far...

**Comment by LeoKlaus** [comment]
I'll have to set up a simulator with iOS 16 to verify this, I'll let you know once I know more!

**Comment by LeoKlaus** [comment]
This was indeed related to iOS 16. I've fixed this with update 1.1.1 which should release in the coming days.

**Comment by mutschler** [comment]
Awesome. I'll check and report back :)

**Comment by LeoKlaus** [comment]
> Awesome. I'll check and report back :)

Great! Keep in mind that the update is not live yet, I'll let you know once it is.

**Comment by LeoKlaus** [comment]
1.1.1 is now live on the AppStore! You might have to check manually for the update as it's just been released.

**Comment by mutschler** [comment]
Seem's to work now :)
