### ISSUE TITLE
[Feature Request] Audiobookshelf SSO Login Not Supported

### ISSUE THREAD

**Issue by JamesRy96** [LeoKlaus/plappa#35]
Add support for SSO auth with Audiobookshelf. 

SSO logins are not supported. Audiobookshelf allows you to set Allowed Mobile Redirect URIs To support SSO in third-party apps.

**Comment by LeoKlaus** [comment]
> Audiobookshelf allows you to set Allowed Mobile Redirect URIs To support SSO in third-party apps.

That's a very helpful remark! Thank you. My highest priority right now is fixing the connection issue some people seem to have, but support for SSO is definitely something I want to implement!

**Comment by LeoKlaus** [comment]
I've just released a TestFlight build with SSO support. The update will probably release to the AppStore in the coming days.
