### ISSUE TITLE
[BUG] ABS - Login without password

### ISSUE THREAD

**Issue by JanJastrow** [LeoKlaus/plappa#37]
Hi, I just heard about plappa and wanted to try it with my Audiobookshelf installation.
Sadly I can't get past the login screen, as I have not set a password for my user and the login screen does not let me proceed with an empty password field.

Can you add support for this?

**Comment by LeoKlaus** [comment]
Sure, I didn't even know that was a thing!

**Comment by LeoKlaus** [comment]
I've added this with update 1.1.1. It's already submitted and awaiting review by Apple. It should release in the coming days.
