### ISSUE TITLE
[BUG] Emby Support of library type "Audio books" 

### ISSUE THREAD

**Issue by secretcapy** [LeoKlaus/plappa#38]
**Describe the bug**
When connecting to an Emby server, nothing shows. It might be due to the library type being set to "Audio books" instead of "Books" as per [this reddit comment](https://old.reddit.com/r/selfhosted/comments/1bwmfds/introducing_plappa_an_audibookshelfjellyfinemby/ky7wfu7/).

Creating an Issue to track the progress of this bug

**Comment by LeoKlaus** [comment]
Hey secretcapy, thanks for creating an issue for this, this helps me keep track.

I just tested this on a test setup and was able to use a library of type "Audio books" just fine. Is there anything "unusual" with your setup for audiobooks in Emby (i.e. any plugins, special folder structure or similar)?

I personally don't use Emby so I only have a small test instance with a couple of audiobooks, maybe I'm missing something?

**Comment by secretcapy** [comment]
Hello LeoKlaus, thank you for looking into this. There's nothing really unusual about my setup except that it's huge library (over 200k audiobooks). There is no plugins or special folder structure, but every author has their own respective folder.

Thanks!

**Comment by LeoKlaus** [comment]
Oh, I see. I've ran some tests with a similarly large library (might even be the same), and have to say that for now, plappa won't work with libraries that large.


plappa downloads the basic metadata for all audiobooks while starting, for 200k books, that's a 150MB json (that the server takes ~30s to even provide).
Supporting libraries that large would require a redesign of the entire underlying structure, so it's likely not going to happen (soon).
