### ISSUE TITLE
[Feature request] Playback speed

### ISSUE THREAD

**Issue by shimi-ke** [LeoKlaus/plappa#4]
The ability to change the playback speed by 0.1x increments would be great. The current 0.25x options are quite big jumps. Maybe adding just 0.9x and 1.1x options would suffice.

**Comment by LeoKlaus** [comment]
Great idea. I've just added 0.9x and 1.1x as options. You might have to manually update through the TestFlight app to get the update, otherwise it will probably be installed next time you charge your phone.

**Comment by LeoKlaus** [comment]
Just wanted to add:
Technically, 0.1 steps wouldn't be hard to implement, but CarPlay does only allow for a fixed preset of speeds and I rather keep the options consistent between CarPlay and the "normal" app.
