### ISSUE TITLE
[BUG] player is not remembering playback speed between sessions

### ISSUE THREAD

**Issue by boomschtick** [LeoKlaus/plappa#41]
**Describe the bug**
When I set a playback speed of anything other than 1.0x, if I close the app and re-open, it'll be set back to 1.0x.

**To Reproduce**
1.  Open app
2. Play a book
3. set speed to different than 1.0x
4. Close plappa
5. re-open plappa
6. play the same book and note the playback speed

**Expected behavior**
The app should remember my playback speed preference.  Not only in this title, but across all titles.

**Environment(please complete the following information):**
Device: iPhone 14
OS: iOS 17.3.1
Version 1.1.0
Server Version ABS 2.8.1

**Comment by LeoKlaus** [comment]
Hey boomschtick,

I've already implemented this with the upcoming 1.1.1 update. It's currently in review with Apple and should release shortly. I'll leave this issue open until the update is released.

**Comment by boomschtick** [comment]
Thanks man

**Comment by LeoKlaus** [comment]
1.1.1 is now live on the AppStore. You might have to manually check for the update, it was just released.

**Comment by boomschtick** [comment]
I did a manual update and did get 1.1.1
