### ISSUE TITLE
[BUG] CarPlay - New Chapter Timestamp Does Not Update

### ISSUE THREAD

**Issue by mandopatriot** [LeoKlaus/plappa#51]
**Describe the bug**
During CarPlay of an Audiobook from ABS, when a chapter ends and a new chapter starts, the chapter number will change but the timestamp is stuck at the previous chapters position. This does not impact the actual audiobook playing as it plays the next chapter properly. Pausing the book will cause it to readjust the timestamp properly.

**To Reproduce**
1. Play audiobook with chapters from ABS with CarPlay.
2. Wait until chapter ends and new chapter starts.
3. Observe timestamp does not update but chapter number does and no impact to audiobook playing.

**Expected behavior**
Timestamp updates to beginning of new chapter without any user intervention during CarPlay.

**Screenshots**
Will try to get a picture during my next time using CarPlay.

**Logs**
Are logs needed?

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.3.1
 - Version: 1.1.1
 - Server Version: ABS 2.3.1 docker

**Additional context**
N/A

**Comment by mandopatriot** [comment]
![IMG_6522](https://github.com/LeoKlaus/plappa/assets/165839892/d29f3ca7-3dc6-4fff-94b5-25c5dc2acd47)
![IMG_6523](https://github.com/LeoKlaus/plappa/assets/165839892/83b2222d-5904-430a-8cb9-2af72ca51bb7)

**Comment by mandopatriot** [comment]
Please don’t mind my dusty car 😂

**Comment by LeoKlaus** [comment]
I just fixed this, the corresponding update should release in the next week.
