### ISSUE TITLE
[BUG] Unable to use skip buttons on Bluetooth device while playing audio from an AudioBookShelf server.

### ISSUE THREAD

**Issue by RobbyMeeker** [LeoKlaus/plappa#54]
**Describe the bug**
While playing audio from an AudioBookShelf server through a Bluetooth device, (car stereo or headphones) the skip back or forward media control buttons on the Bluetooth device do nothing when pressed. Play/pause however works fine. 

**To Reproduce**
1. Open app.
2. Play media from AudioBookShelf server through Bluetooth device.
3. Notice that pressing the skip back/forward buttons on said device does nothing when pressed. 

**Expected behavior**
Pressing skip back/forward buttons on Bluetooth devices should function as described.

**Environment(please complete the following information):**
 - Device: [iPhoneXr]
 - OS: [iOS17.4.1]
 - Version [1.1.1]
 - Server Version [AudioBookShelf 2.8.1]

Other apps on this iPhone do not experience this behavior.

**Comment by LeoKlaus** [comment]
I just fixed this, a corresponding update should release shortly.

**Comment by RobbyMeeker** [comment]
> I just fixed this, a corresponding update should release shortly.

Sweet, thanks!

**Comment by scapix** [comment]
hello
not fixed in 2.13.4
iphone 15 pro max
ios 18
update: hmmm... in some instances it works ok. trying to find out more details

**Comment by LeoKlaus** [comment]
Hey @scapix can you tell me what version of plappa you're running? You can see it in the "About plappa" section in the settings tab.

Did you have issues with the forward/backward commands or the play/pause. A new issue has been created for the behavior of the play/pause button in #195.
