### ISSUE TITLE
[Feature Request] Add total track seekbar option

### ISSUE THREAD

**Issue by Schabernack** [LeoKlaus/plappa#56]
**What**

Currently, the seekbar only shows the position within a chapter. Add a seekbar that tracks progress through the entirety of the book.

This could be configurable: Either switch out the current seekbar and toggle between chaper/book progress. Or make it an option to display 1 or 2 progress bars at the same time.  

Solution 2) is what ABS allows. Personally i think it looks a bit awkward and I would go for 1) but i want to keep this  solutioning open ended :)

**Why**

I mainly listen to audiobooks between 50-70 minutes of length. A lot of them have like 20 chapters, each with like 1-5 minutes length.  That makes looking at chapter progress almost useless. And it makes it very hard to jump to an arbitrary position in the book (i.e. i feel asleep and need to scroll back ten minutes). The only way to do this right now is the chapter select, but that is rather clunky and also due to non-uniform chapter lengths does not make it immediately obvious how far you are going back or how far into the book you are. 

**Notes**

Amazing app ❤️. Thanks for all the effort put you put into this  Leo  

**Screenshots**
ABS screenshots on the config setting, the 2 track solution and the total progress track bar. 

<img src="https://github.com/LeoKlaus/plappa/assets/155029/d9cf00b8-848e-487f-9a55-11c7fc93d5e4" width=230px>

<img src="https://github.com/LeoKlaus/plappa/assets/155029/96fb04ce-176d-454f-889d-b0e8cda997dc" width=230px>

**Comment by LeoKlaus** [comment]
Hey Nicolas, thanks for the suggestion and the kind words!

I think this is a great idea. I'll have to see whether this is easily possible with the current architecture or if this requires some more extensive changes under the hood.

If you have any other feedback or suggestions, feel free to let me know!

**Comment by ajyey** [comment]
@LeoKlaus Just throwing my support in for this as well.

I actually think that the way Prologue does it is the best. A single seek bar for the current chapter and then showing the time remaining for the entire book under it

![CleanShot 2024-07-16 at 00 19 03@2x](https://github.com/user-attachments/assets/a8099615-b6b1-4f59-a034-924308709be7)
