### ISSUE TITLE
[BUG] App Icon not updating

### ISSUE THREAD

**Issue by PleaseStopAsking** [LeoKlaus/plappa#57]
**Describe the bug**
When switching the app icon, it is not reflected on the app icon on device nor via CarPlay in a uniform manner. It showed up after five (5) minutes or so in only one (1) of the three locations listed below.

Locations:
- Device Icon
- CarPlay Icon
- CarPlay recently used sidebar (`working`)

**To Reproduce**
1. Switch app icon in plappa setting
2. Check app icon

**Expected behavior**
The new app icon should be shown on the springboard and within CarPlay.

**Screenshots**
![IMG_9255](https://github.com/LeoKlaus/plappa/assets/35308946/9f02bae0-19df-4f6c-a007-c28010f5a4c1)

![D8E104F6-66B2-41B0-AD7B-08FCABA46299_1_102_o](https://github.com/LeoKlaus/plappa/assets/35308946/5ac2adeb-6030-4bb9-9364-1ad994526150)

**Environment(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.4.1
 - Version" 1.1.2
 - Server Version: ABS v2.8.1

**Comment by LeoKlaus** [comment]
Hey Michael,

Thanks for reporting this.

plappa is using the default system apis to change the app icon, I don't have any influence on when or if the change is actually performed.

Interestingly enough, I've recently had a similar issue with Signal, maybe something broke with a recent update (my personal iPhone is on 17.5).

What always does the trick in my experience is restarting the phone.

**Comment by PleaseStopAsking** [comment]
Restarting the device did the trick.

I assumed this was a iOS issue but wanted to open a ticket to document it in the event others ran into the same issue. I will close this one out.
