### ISSUE TITLE
[BUG] Carplay skip don't work

### ISSUE THREAD

**Issue by karolismatulevicius** [LeoKlaus/plappa#58]
**Describe the bug**
When using Carplay, skip doesn't work. Also, skip icons differ between 'Now playing' and Overview views.

**Screenshots**
![IMG_0524](https://github.com/LeoKlaus/plappa/assets/37836792/4c95c089-80c1-4039-a398-caa3e7cc4f90)

![IMG_0522](https://github.com/LeoKlaus/plappa/assets/37836792/d762453e-0e4f-4196-891e-91450a348f2e)

**Logs**
If applicable, add logs from plappa (Settings->Get Debug Logs) or Jellyfin (Dashboard->Advanced->Logs).

**Environment(please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17.4.1
 - Server Version: Audiobookshelf v2.8.1

**Additional context**

**Comment by LeoKlaus** [comment]
Hey Karolis, thanks for reporting this.

I probably won't have time to take a closer look at this until Friday but I'll let you know once I have more info.

Did you set custom values for the skip times?

**Comment by karolismatulevicius** [comment]
Hi Leo,
No, they are default 15 seconds

**Comment by karolismatulevicius** [comment]
Hi, also noticed that I can't skip on iPhone lock-screen and on Apple watch 'Now Playing' screen
![IMG_0523](https://github.com/LeoKlaus/plappa/assets/37836792/d87c2139-8c76-4720-90a4-35da39c30dff)

**Comment by LeoKlaus** [comment]
I've been able to reproduce this on a fresh install of plappa.

It's weird that this happens as there are default values in place but I was able to fix it by choosing any skip time that's not 15 seconds (and reverting back to 15s). After you do that, just pause and resume playback to update the interface.

I'll have to look into why this happens but with the above workaround you should be able to fix the issue for now.

**Comment by LeoKlaus** [comment]
I've found and fixed the issue. The corresponding update should release in the coming week!
