### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ElmarMuc** [LeoKlaus/plappa#63]
**Describe the bug**
The list of the chapters is random and it is not the same at as in audio bookshelf
**To Reproduce**
![IMG_F8C06E971CED-1](https://github.com/LeoKlaus/plappa/assets/144257936/fde1b372-4f1b-4a5e-b3d2-bd3018ade07f)

**Comment by LeoKlaus** [comment]
Hey Elmar, this is usually fixed by using the "pull to refresh" gesture while viewing the book (looking at the chapters).

**Comment by LeoKlaus** [comment]
I've added some improvements around chapter handling, coming with the next update.
