### ISSUE TITLE
[BUG]  “end of chapter” sleep timer not in sync when playing at different speed

### ISSUE THREAD

**Issue by vankempen** [LeoKlaus/plappa#64]
**Describe the bug**
When selecting “end of Chapter” as the sleep timer option while playing at a different speed then 1x (eg 1.25x), the playing will not stop at end of chapter. 

**To Reproduce**
1. Listen to audiobook
2. Change playback speed to 1.25
3. Select sleep timer ‘end of chapter’
4. Wait till end of chapter, and notice that it will continue, and stop at a later moment.

**Expected behavior**
Stop blayback at end of chapter

**Screenshots**
N/A

**Logs**
N/A
**Environment(please complete the following information):**
 - Device: iPhone 14
 - OS: ios17.4.1
 - Version 1.1.2
 - Server Version audiobookshelf 2.8.1

**Additional context**
N/A

**Comment by LeoKlaus** [comment]
Great catch! I'll take care of this.

**Comment by LeoKlaus** [comment]
I've found a much better way to handle this, will release with the next update!
