### ISSUE TITLE
[BUG] Seek settings do not work "out of box"

### ISSUE THREAD

**Issue by ShadowPeo** [LeoKlaus/plappa#65]
Upon first use/install seek (x seconds forward/back) did not work, had to change this in settings away from want it was set at (15) and back again to get it to work

**To Reproduce**
1. Install App
2. Add AB library
3 play 
4. Try to seek

**Expected behavior**
Seek to work without having to "set" it

**Screenshots**

**Logs**
If applicable, add logs from plappa (Settings->Get Debug Logs) or Jellyfin (Dashboard->Advanced->Logs).

**Environment(please complete the following information):**
 - Device: iPhone Pro 12 Max
- iOS 17.4.1

**Comment by LeoKlaus** [comment]
Hey Justin,

Thanks for reporting this. I'm already tracking this issue in #58.

A fix is already implemented and will release shortly.

If you have any other feedback or suggestions, feel free to let me know!

**Comment by ShadowPeo** [comment]
Thanks the GitHub app does not seem to be showing all the open issues to me then
