### ISSUE TITLE
[BUG] Seek settings get wiered if trying to seek and carplay makes an announcement 

### ISSUE THREAD

**Issue by ShadowPeo** [LeoKlaus/plappa#66]
When paused when using CarPlay due to another announcement (Maps in my test case) and your seeking (in either direction) it goes from seconds to an exactly 25 minute jump. When it goes back to playing after the announcement seek works correctly again, however if you pause the 25min seek is still in effect (so if I pause it after tagging this bug it will seek by 25 min, play will work correctly) closing and reopening the app corrects this but I suspect changing the book played would as well

**To Reproduce**
1. Have book playing whilst using CarPlay (wireless in my case cannot test wired)
2. Be seeking forward or reverse in a book when an navigation (or I suspect any) announcement is made
3. The seeks during the announcement will be exactly 25 minutes not the set week time 
4. Pausing after this 25 minute seek issue has been trigged will exhibit the same symptoms seeking during the paused play period but if playing correct seek setting will be used

**Expected behavior**
Seek to work with a consistent time or not work during the paused for announcement 

**Environment(please complete the following information):**
 - Device: iPhone Pro 12 Max
- iOS 17.4.1

**Comment by LeoKlaus** [comment]
Hey Justin, thank you very much for reporting this!

I've found and fixed the issue. A corresponding update will reach TestFlight today and the AppStore in the coming week!
