### ISSUE TITLE
[Feature Request] Bookmark directly in the player

### ISSUE THREAD

**Issue by mrburns-42** [LeoKlaus/plappa#72]
**What?**
It would be great if you could access the set bookmarks directly in the player.

**Why?**
If I want to continue listening at a point where I have set a bookmark, I currently have to open the book from the start screen and click on Bookmarks. However, I am often already in the player view and therefore have to leave it and search for the audiobook again and open the details.

**Current possibility to access bookmarks**
![IMG_6727](https://github.com/LeoKlaus/plappa/assets/786982/1e8ba2d4-bb97-44e3-8722-f2063b631470)

**How could this be implemented?**
In the player view, you already have the option to click on chapters. An overview of the chapters will then open so that you can select another one if necessary. Perhaps the bookmarks could also be listed here ... e.g. by allowing you to switch between chapters and bookmarks at the top.

**The part of the player I am writing about**
![IMG_6728](https://github.com/LeoKlaus/plappa/assets/786982/99db07a2-d9de-4da2-bf1c-0f6fd9bd41fc)

**Comment by LeoKlaus** [comment]
I've added this with one of the last releases (I don't remember which one exactly but you should already have it).

**Comment by mrburns-42** [comment]
@LeoKlaus I seem to be overlooking something, I can't find the option. How do I get to it?

**Comment by LeoKlaus** [comment]
> @LeoKlaus I seem to be overlooking something, I can't find the option. How do I get to it?

While in the player, open the bookmarks list (scroll to the top if necessary) and tap on "Bookmarks":
![image](https://github.com/user-attachments/assets/cee0ba6d-cafd-4e2d-8b5c-2ef53eecde11)

**Comment by LeoKlaus** [comment]
Now that I think of it, the picker shouldn't be within the scrollview...

**Comment by mrburns-42** [comment]
> > @LeoKlaus I seem to be overlooking something, I can't find the option. How do I get to it?
> 
> While in the player, open the bookmarks list (scroll to the top if necessary) and tap on "Bookmarks":

Thank you very much. I didn't realize I had to scroll up. Maybe you could fix the bar with the selection of chapters and bookmarks?
