### ISSUE TITLE
[BUG] Tapping on menu item does not go back to main menu

### ISSUE THREAD

**Issue by Drikani** [LeoKlaus/plappa#81]
**Describe the bug**
When within the detail screen of a book or a series you can only go back when swiping from the left or by tapping on the "< Back" button on the top left.
It should also be possible to go back within the menus by tapping on the same menu item again.

**To Reproduce**
1. Go to Series Menu
2. Open a Series
3. Tap on Series Icon in Bottom Menu
4. Nothin happens

**Expected behavior**
It should bring you back to the Series overview like when you swipe from the left

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.4.1
 - Version 1.1.4
 - Server Version Audiobookshelf 2.9.0

**Comment by LeoKlaus** [comment]
I finally got around to this. Technically, this was a feature request, not a bug.

Moving back to the root of a tab on the second press is _not_ default behavior in SwiftUI, even if Apples own apps basically all do this.

Anyway, it's implemented with the latest TestFlight release (1.4.0 build 39) and will come to the AppStore with the next update.

**Comment by Drikani** [comment]
Perfect it works on all the content tabs.
Is it intentional that it does not work on the settings tab as well?
