### ISSUE TITLE
[BUG] Download stops when plappa App

### ISSUE THREAD

**Issue by ElmarMuc** [LeoKlaus/plappa#82]
I tried to download an m3u file. About 1 gbyte
 When I switched the app the download stopped. It could not be resumed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add logs from plappa (Settings->Get Debug Logs) or Jellyfin (Dashboard->Advanced->Logs).

**Environment(please complete the following information):**
 - Server Version [e.g. Jellyfin 10.8.13]

**Additional context**
Add any other context about the probl.

**Comment by ShadowPeo** [comment]
Can confirm this bug as a general bug as I get it with MP4s

**Comment by LeoKlaus** [comment]
Hey, thank you for reporting this! There's already an issue for this at #42, so I'll close this.

I'll let you know once I have more information on this. For now, the only way to have downloads finish reliably is keeping the screen of your phone awake while downloading and not switching the app.
