### ISSUE TITLE
[Enhancement] Change Seek and Volume Bar behaviour to be like in Apple Music

### ISSUE THREAD

**Issue by Drikani** [LeoKlaus/plappa#85]
It would be really cool if the Progress and Volume Bar would operate like within Apple Music.
First it should be controllable regardless if you start moving it at the point it is right now.
Also it should get a little bigger when being interacted with.

This would make the app feel much more in line with the other apps and make it easier to interact with.

Here is a reference video to show what I mean (Start at 1:51 or Chapter 6):
[Youtube-Demo](https://youtu.be/XtCWd8htwCE?si=P8MeOcYIIIZu515W&t=111)

**Comment by ShadowPeo** [comment]
Seconded

**Comment by LeoKlaus** [comment]
I've added this with the latest 1.2.0 update.
