### ISSUE TITLE
[FEATURE REQUEST] Support audiobook series

### ISSUE THREAD

**Issue by Teonyr** [LeoKlaus/plappa#9]
Hey,
firstly I'd like to express that I really enjoy using your app - keep up the great work!

Though there is a feature I would like to see in an upcoming version:
Support for series / collections of audiobooks.

**Screenshot from Audiobookshelf**
![grafik](https://github.com/LeoKlaus/plappa/assets/75175693/769b938c-b1b0-4c24-9287-e1576748ac8a)

As you can see I have not the greatest but still a quite extensive collection of audiobooks.
Currently browsing all those books by clicking on "Books"-tab in the Plappa app isn't enjoyable at all. 😅 

I hope this feature could help improve the performance, since on my iPhone 15 Pro Max the "Book"-tab is noticeably struggling with the sheer amount of audiobooks it needs to display.

Cheers.

**Comment by LeoKlaus** [comment]
Wow, that is quite the collection!

I'm already working on support for collections and series', but it's not quite ready yet.

I've just released another update to TestFlight that should improve performance in the "Books"-tab, I think this should help until I manage to get series' and collections working.

**Comment by Teonyr** [comment]
Great thanks 👍🏻
Indeed, performance in v. 0.9 (18) is way better than before.

**Comment by LeoKlaus** [comment]
I've just released an update (build 21) that adds support for series. Collections will come later.

**Comment by LeoKlaus** [comment]
TestFlight build 22 (or 1.0.0 build 1) includes support for collections as well. Marking this as closed now, if you have any other feedback, let me know!

If you feel like anything is missing with collections or series, feel free to reopen this.
