### ISSUE TITLE
[BUG] Click and hold download does not work

### ISSUE THREAD

**Issue by ShadowPeo** [LeoKlaus/plappa#90]
**Describe the bug**
Clicking on the book name and clicking download does not seem to start the download, if I open the book or any book for that matter the download will start but trying multiple downloads using click and hold (I was trying three) does not work at all even opening a book to get it, only the most recent click and hold click download shows up

**To Reproduce**
Click and hold, select download. 
No download session is initiated

Click and hold,click download
Open any book
Open download page
Book is downloading
**Expected behavior**

Click and hold, click download
Repeat this on multiple books
Open any book, download is only working for most recent book

**Expected Behaviour**
Download to be added to queue and initiated straight away not having to open a book to have the queue update and download start 

**Screenshots**

**Logs**
If applicable, add logs from plappa (Settings->Get Debug Logs) or Jellyfin (Dashboard->Advanced->Logs).

**Environment(please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS
 - Version 17.4.1
 - Server Version AudioBookshelf 2.9.0

**Comment by LeoKlaus** [comment]
Hey again Justin, thank you for reaching out!

The file metadata is only loaded when a book is opened the first time, before that, the download button from the context menu doesn't work (reliably). After opening it the first time, you can download a book through the context menu.

There is some logic in place to load the metadata when using the context menu button, but it doesn't work reliably as of now.

**Comment by LeoKlaus** [comment]
This should be fixed with the latest beta release of 1.4.0. If you still encounter this issue, feel free to reopen this!
