### ISSUE TITLE
[BUG] Finished book is not marked as finished in ABS

### ISSUE THREAD

**Issue by mrburns-42** [LeoKlaus/plappa#92]
**Describe the bug**
If I listen to a book to the end in Plappa, it is marked as finished in Plappa, but not in ABS. 

**To Reproduce**
1. Listen to an audiobook to the end in Plappa
2. Go to the ABS app
3. Search the audiobook
4. The audiobook is finished, but not marked as finished

**Expected behavior**
If an audio book has been finished in Plappa, this should also be marked as finished in ABS.

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.4.1
 - Version 1.1.5 (2)
 - Server Version ABS 2.9.0

**Additional context**
Marking a book as finished has several advantages:

1. the book is listed in ABS among the finished audiobooks and can be filtered accordingly.
2. the book is listed in ABS under Listen again.
3. if the book is part of a series, the next volume will be displayed under Continue series.

**Comment by mrburns-42** [comment]
The problem does not always seem to occur. I have just finished an audiobook which was correctly marked as finished. This was not the case with the previous three.

**Comment by mrburns-42** [comment]
Sorry for the many entries, there's an update: I just checked ABS again and the book was no longer marked as finished. The progress was back to 0 percent. In the meantime, I deleted the local copy of the book in Plappa and started another book ... nothing more.

**Comment by wfrank21** [comment]
Having the same issue here. Jellyfin and ABS. No playback time is recorded in the statistics of ABS as well.

**Comment by mrburns-42** [comment]
@wfrank21 Then at least I'm not alone with the problem. The fact that the listening time does not appear in the ABS statistics must be due to the fact that the ABS listening sessions #15 have not yet been implemented.

**Comment by LeoKlaus** [comment]
Thank you both for reporting this!

I believe I have identified the issue and implemented a fix, it is available in TestFlight now (1.1.5 build 10).

**Comment by mrburns-42** [comment]
@LeoKlaus I will test it and will give you a feedback.

**Comment by wfrank21** [comment]
@LeoKlaus How long until this will be available on TestFlight? I only see 1.1.5 (8)

**Comment by LeoKlaus** [comment]
> @LeoKlaus How long until this will be available on TestFlight? I only see 1.1.5 (8)

I've only released it to a group you're not part of, my bad. Should be available to you now.

**Comment by wfrank21** [comment]
Thanks! For me the bug is resolved, Episodes are marked as read in ABS

**Comment by mrburns-42** [comment]
I have also tested it, it works now. Many thanks for your efforts.

**Comment by LeoKlaus** [comment]
Great, I'll close this, then!
