### ISSUE TITLE
[Feature Request] Use original covers instead of thumbnails

### ISSUE THREAD

**Issue by uwuceo** [LeoKlaus/plappa#98]
For AudioBookShelf (haven't tested if with Jellyfin), on pages where the covers are bigger (in-app player, control center player), it's quite noticeable that the covers are low res.

I understand that it might not be possible to use the original cover everywhere (might be a couple of MB each), but I think it would be nice to use the original at least where it's most noticeable that the thumbnails are small.

Thumbnail:

/api/items/28d3e951-3299-4c83-b348-bfa742de03d3/cover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZTJjMjEwNy1lNjdlLTRlM2ItYWE5ZS0wYmVkM2FkZmNhNWQiLCJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE2OTY5NTEzMzR9.rb__5n34HTTF5fUemIbLNnQ0taJbaDBf2q4xs_ypIBs&ts=1710115243987

Original:

/api/items/28d3e951-3299-4c83-b348-bfa742de03d3/cover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZTJjMjEwNy1lNjdlLTRlM2ItYWE5ZS0wYmVkM2FkZmNhNWQiLCJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE2OTY5NTEzMzR9.rb__5n34HTTF5fUemIbLNnQ0taJbaDBf2q4xs_ypIBs&raw=1&ts=1710115243987

**Comment by LeoKlaus** [comment]
I initially used the 'raw' parameter but noticed it would lead to server crashes when no cover file was present.
I'll check whether this is still an issue or if I can switch to the raw image.

**Comment by uwuceo** [comment]
The official ABS app uses the raw, from what I can tell, for the 2 players (in-app, iOS) and when you select a book. I wouldn't be surprised if they use the raw version everywhere, but for those places I'm 100% sure, as the covers are smaller elsewhere, and it's harder to tell.

The app's on github so can maybe you check how they do it?

**Comment by LeoKlaus** [comment]
I've changed it now. Will release an update to TestFlight as soon as it's approved by Apple.
