### ISSUE TITLE
[BUG] In-app player times moving

### ISSUE THREAD

**Issue by uwuceo** [LeoKlaus/plappa#99]
**Describe the bug**
During playback, the times move and the URL gets trimmed differently almost each second.

**To Reproduce**
1. Go to the in-app player with something playing
2. See error

**Expected behavior**
The location of the times to be fixed, and not move around once per second.

**Screenshots**

https://github.com/LeoKlaus/plappa/assets/76777112/1eca7b39-cb81-46c5-a203-37b73ef6a159

**Environment (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16.7.7.
 - Version 1.15 (12)
 - Server Version ABS 2.9.0

**Additional context**
I believe it is due to the character width of the times changing (audio players usually use monospaced fonts for times), the fact that the server URL is trimmed, and how they are displayed.

**Comment by LeoKlaus** [comment]
That's pretty distracting, I'll make sure to fix it with the next update.

**Comment by uwuceo** [comment]
It’s less distracting after the update, but the times still move around a bit due to the font not being monospaced. 

https://github.com/LeoKlaus/plappa/assets/76777112/80658abb-9dff-446b-919f-66d33b7e8fd1

Here are a couple of examples: Spotify uses a monospaced font, but I’m not sure what the iOS player uses.

https://github.com/LeoKlaus/plappa/assets/76777112/3d4edfd5-4327-4c45-bb79-30bf0c2efe8b


https://github.com/LeoKlaus/plappa/assets/76777112/1321eb4c-4bcc-48e5-9742-48f1dc08cdc4
